import type { URLScheme } from '@/types'

const APP_STORE: readonly URLScheme[] = [
  {
    id: 'app-store-ios',
    name: 'iOS App Store 应用详情',
    category: 'app_store',
    urlTemplate: 'itms-apps://itunes.apple.com/cn/app/<bundle_id>/id<apple_id>',
    slots: [
      {
        name: 'bundle_id',
        description: '应用的 Bundle ID',
        placeholder: '例如：wechat',
        required: true,
      },
      {
        name: 'apple_id',
        description: 'Apple 分配的应用 ID',
        placeholder: '例如：414478124',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 iOS App Store 中指定应用的详情页面',
    examples: [
      'itms-apps://itunes.apple.com/cn/app/wechat/id414478124',
      'itms-apps://itunes.apple.com/cn/app/qq/id444934666',
    ],
  },
  {
    id: 'app-store-android',
    name: 'Android 应用商店详情',
    category: 'app_store',
    urlTemplate: 'market://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: 'Android 应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 Android 应用商店中指定应用的详情页面',
    examples: [
      'market://details?id=com.tencent.mm',
      'market://details?id=com.tencent.mobileqq',
    ],
  },
  {
    id: 'google-play',
    name: 'Google Play 商店',
    category: 'app_store',
    urlTemplate: 'https://play.google.com/store/apps/details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: 'Android 应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 Google Play 商店中的应用详情页面',
    examples: ['https://play.google.com/store/apps/details?id=com.tencent.mm'],
  },
  {
    id: 'huawei-appgallery',
    name: '华为应用市场',
    category: 'app_store',
    urlTemplate: 'appmarket://details?pkgname=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开华为应用市场中的应用详情页面',
    examples: ['appmarket://details?pkgname=com.tencent.mm'],
  },
  {
    id: 'xiaomi-appstore',
    name: '小米应用商店',
    category: 'app_store',
    urlTemplate: 'https://app.mi.com/details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开小米应用商店中的应用详情页面',
    examples: ['https://app.mi.com/details?id=com.tencent.mm'],
  },
  {
    id: 'oppo-appstore',
    name: 'OPPO 应用商店',
    category: 'app_store',
    urlTemplate: 'market://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 OPPO 应用商店中的应用详情页面',
    examples: ['market://details?id=com.tencent.mm'],
  },
  {
    id: 'vivo-appstore',
    name: 'vivo 应用商店',
    category: 'app_store',
    urlTemplate: 'vivomarket://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 vivo 应用商店中的应用详情页面',
    examples: ['vivomarket://details?id=com.tencent.mm'],
  },
  {
    id: 'meizu-appstore',
    name: '魅族应用商店',
    category: 'app_store',
    urlTemplate: 'market://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开魅族应用商店中的应用详情页面',
    examples: ['market://details?id=com.tencent.mm'],
  },
  {
    id: 'samsung-appstore',
    name: '三星应用商店',
    category: 'app_store',
    urlTemplate: 'samsungapps://ProductDetail/<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开三星应用商店中的应用详情页面',
    examples: ['samsungapps://ProductDetail/com.tencent.mm'],
  },
  {
    id: 'honor-appstore',
    name: '荣耀应用商店',
    category: 'app_store',
    urlTemplate: 'market://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开荣耀应用商店中的应用详情页面',
    examples: ['market://details?id=com.tencent.mm'],
  },
  {
    id: 'tencent-appstore',
    name: '应用宝',
    category: 'app_store',
    urlTemplate: 'tmast://appdetails?pname=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开应用宝中的应用详情页面',
    examples: ['tmast://appdetails?pname=com.tencent.mm'],
  },
  {
    id: 'coolapk',
    name: '酷安',
    category: 'app_store',
    urlTemplate: 'coolmarket://com.coolapk.market/apk/<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开酷安中的应用详情页面',
    examples: ['coolmarket://com.coolapk.market/apk/com.tencent.mm'],
  },
] as const

export default APP_STORE
