import type { UrlSchemeWithoutCategory } from '@/types'

const CHROME: UrlSchemeWithoutCategory[] = [
  {
    id: 'chrome-chrome-urls',
    name: '可用列表',
    description: '查看 Chrome 所有可用的 chrome:// 页面',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://chrome-urls',
    examples: ['chrome://chrome-urls', 'chrome://about'],
  },
  {
    id: 'chrome-newtab',
    name: '新标签页',
    description: '在 Chrome 打开一个新的标签页',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://newtab',
    examples: ['chrome://newtab'],
  },
  {
    id: 'chrome-extensions',
    name: '扩展程序',
    description: '打开 Chrome 扩展程序',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://extensions',
    examples: ['chrome://extensions'],
  },
  {
    id: 'chrome-bookmarks',
    name: '书签管理器',
    description: '打开 Chrome 书签管理器',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://bookmarks',
    examples: ['chrome://bookmarks'],
  },
  {
    id: 'chrome-history',
    name: '历史记录',
    description: '打开 Chrome 全部历史记录',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://history',
    examples: ['chrome://history'],
  },
  {
    id: 'chrome-downloads',
    name: '下载记录',
    description: '打开 Chrome 下载记录',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://downloads',
    examples: ['chrome://downloads'],
  },
  {
    id: 'chrome-settings',
    name: '设置',
    description: '打开 Chrome 设置页面',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://settings',
    examples: ['chrome://settings'],
  },
  {
    id: 'chrome-settings-help',
    name: '设置-关于 Chrome',
    description: '打开 Chrome 检查更新、帮助和报告问题',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://settings/help',
    examples: ['chrome://settings/help'],
  },
  {
    id: 'chrome-apps',
    name: 'Web 应用',
    description: '打开 Chrome 安装的 Web 应用',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://apps',
    examples: ['chrome://apps'],
  },
  {
    id: 'chrome-inspect',
    name: '调试',
    description: '打开 Chrome 调试（包含设备、页面、扩展、Workers 等）',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://inspect',
    examples: ['chrome://inspect'],
  },
  {
    id: 'chrome-flags',
    name: '实验性功能',
    description: '打开 Chrome 实验性功能',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://flags',
    examples: ['chrome://flags'],
  },
  {
    id: 'chrome-version',
    name: '版本信息',
    description: '查看 Chrome 版本信息',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://version',
    examples: ['chrome://version'],
  },
  {
    id: 'chrome-whats-new',
    name: '新变化',
    description: '查看当前 Chrome 版本新变化',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://whats-new',
    examples: ['chrome://whats-new'],
  },
  {
    id: 'chrome-crashes',
    name: '崩溃报告',
    description: '查看 Chrome 崩溃报告',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://crashes',
    examples: ['chrome://crashes'],
  },
  {
    id: 'chrome-system',
    name: '系统诊断',
    description: '查看 Chrome 系统诊断数据',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://system',
    examples: ['chrome://system'],
  },
  {
    id: 'chrome-net-internals',
    name: '网络统计',
    description: '打开 Chrome 网络相关的内置工具，提供了监视和调试网络请求与事件的详细功能',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://net-internals',
    examples: ['chrome://net-internals'],
  },
  {
    id: 'chrome-gpu',
    name: 'GPU 信息',
    description: '查看 Chrome GPU 信息',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-27T00:00:00Z',
    urlSchemeTemplate: 'chrome://gpu',
    examples: ['chrome://gpu'],
  },
]

export default CHROME
