import type { UrlSchemeWithoutCategory } from '@/types'

const DOUYIN: UrlSchemeWithoutCategory[] = [
  {
    id: 'douyin-scan',
    name: '扫一扫',
    description: '打开抖音扫一扫',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-12T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/scan',
    examples: ['snssdk1128://aweme/scan'],
  },
  {
    id: 'douyin-hotlist',
    name: '抖音热榜',
    description: '打开抖音热榜',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-12T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://search/trending',
    examples: ['snssdk1128://search/trending'],
  },
  {
    id: 'douyin-webcast-hot-live-rank',
    name: '直播人气榜',
    description: '打开抖音直播人气榜',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://webcast_board/hot_live_rank',
    examples: ['snssdk1128://webcast_board/hot_live_rank'],
  },
  {
    id: 'douyin-user-profile',
    name: '用户主页',
    description: '打开抖音指定用户主页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-12T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://user/profile/{uid}',
    slots: [
      {
        name: 'uid',
        description:
          '用户 ID。在浏览器打开用户主页，在控制台搜索 https://www.douyin.com/aweme/v1/web/aweme/post/，从 aweme_list 其中一条作品里找到 author.uid。',
        placeholder: '3439720764022429',
      },
    ],
    examples: ['snssdk1128://user/profile/3439720764022429'],
  },
  {
    id: 'douyin-aweme-create',
    name: '视频创作',
    description: '打开抖音视频创作（拍摄发布作品）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/create',
    examples: ['snssdk1128://aweme/create'],
  },
  {
    id: 'douyin-aweme-closefriends-moments',
    name: '日常创作',
    description: '打开抖音日常创作',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/closefriends/moments',
    examples: ['snssdk1128://aweme/closefriends/moments'],
  },
  {
    id: 'douyin-familiar',
    name: '首页-朋友',
    description: '打开抖音首页朋友 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/familiar',
    examples: ['snssdk1128://aweme/familiar'],
  },
  {
    id: 'douyin-user-homepage',
    name: '我的',
    description: '打开抖音我的 Tab（登录用户主页）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://user/homepage',
    examples: ['snssdk1128://user/homepage'],
  },
  {
    id: 'douyin-profile-edit',
    name: '我的-编辑主页',
    description: '打开抖音我的编辑主页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://profile_edit',
    examples: ['snssdk1128://profile_edit'],
  },
  {
    id: 'douyin-im-fansPush',
    name: '粉丝求更新',
    description: '打开抖音粉丝求更新列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://im/fansPush',
    examples: ['snssdk1128://im/fansPush'],
  },
  {
    id: 'douyin-aweme-watch-later-list',
    name: '稍后再看',
    description: '打开抖音稍后再看',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/watch_later_list',
    examples: ['snssdk1128://aweme/watch_later_list'],
  },
  {
    id: 'douyin-aweme-detail',
    name: '视频作品',
    description: '打开抖音指定视频作品',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-12T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://aweme/detail/{aweme_id}',
    slots: [
      {
        name: 'aweme_id',
        description: '视频作品 ID',
        placeholder: '7527640622661209371',
      },
    ],
    examples: ['snssdk1128://aweme/detail/7527640622661209371'],
  },
  {
    id: 'douyin-webcast-feed',
    name: '直播广场',
    description: '打开抖音直播广场',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://webcast_feed',
    examples: ['snssdk1128://webcast_feed'],
  },
  {
    id: 'douyin-webcast-room',
    name: '直播间',
    description: '打开抖音指定直播间',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://webcast_room?id={room_id}',
    slots: [
      {
        name: 'room_id',
        description:
          '直播间 ID。在手机上进直播间分享复制链接，在浏览器打开，控制台搜索 https://webcast.amemv.com/douyin/webcast/reflow/7538199105491766056 后面的便是直播间 ID。',
        placeholder: '7538199105491766056',
      },
    ],
    examples: ['snssdk1128://webcast_room?id=7538199105491766056'],
  },
  {
    id: 'douyin-webcast-open-live',
    name: '开直播',
    description: '打开抖音开直播',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://webcast_open_live',
    examples: ['snssdk1128://webcast_open_live'],
  },
  {
    id: 'douyin-ecom-order-list',
    name: '商城-我的订单',
    description: '打开抖音商城订单列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://ecom_order_list',
    examples: ['snssdk1128://ecom_order_list'],
  },
  {
    id: 'douyin-ec-search',
    name: '商城-搜索',
    description: '打开抖音商城搜索',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-14T00:00:00Z',
    urlSchemeTemplate: 'snssdk1128://ec_search',
    examples: ['snssdk1128://ec_search'],
  },
]

export default DOUYIN
