import type { UrlSchemeWithoutCategory } from '@/types'

const IOS: UrlSchemeWithoutCategory[] = [
  {
    id: 'ios-apple-music-redeem',
    name: 'Apple Music 兑换',
    description: '打开 Apple Music 兑换',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/WebObjects/MZFinance.woa/wa/redeemLandingPage',
    examples: ['music://music.apple.com/WebObjects/MZFinance.woa/wa/redeemLandingPage'],
  },
  {
    id: 'ios-music-show-now-playing',
    name: 'Apple Music 播放页',
    description: '打开 Apple Music 播放页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'music://shownowplaying',
    examples: ['music://shownowplaying'],
  },
  {
    id: 'ios-apple-music-home',
    name: 'Apple Music 主页',
    description: 'Apple Music 主页 Tab 页（原现在就听）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/home',
    examples: ['music://music.apple.com/home', 'music://music.apple.com/listennow'],
  },
  {
    id: 'ios-apple-music-browse',
    name: 'Apple Music 新发现',
    description: 'Apple Music 新发现 Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/browse',
    examples: ['music://music.apple.com/browse', 'music://music.apple.com/new'],
  },
  {
    id: 'ios-apple-music-radio',
    name: 'Apple Music 广播',
    description: '打开 Apple Music 广播 Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/radio',
    examples: ['music://music.apple.com/radio'],
  },
  {
    id: 'ios-apple-music-search',
    name: 'Apple Music 搜索',
    description: '打开 Apple Music 搜索',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'music://music.apple.com/search',
    examples: ['music://music.apple.com/search'],
  },
  {
    id: 'ios-apple-music-search-specific-music',
    name: 'Apple Music 搜索内容',
    description: '打开 Apple Music 搜索并搜索指定内容',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/search?term=<keyword>',
    slots: [
      {
        name: 'keyword',
        description: '搜索关键词',
        placeholder: '林奕匡',
      },
    ],
    examples: ['music://music.apple.com/search?term=林奕匡'],
  },
  {
    id: 'ios-apple-music-playlists',
    name: 'Apple Music 播放列表',
    description: '打开 Apple Music 资料库播放列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/library/all-playlists',
    examples: ['music://music.apple.com/library/all-playlists'],
  },
  {
    id: 'ios-apple-music-playlist',
    name: 'Apple Music 指定播放列表',
    description: '打开 Apple Music 播放列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/library/playlist/pl.<playlist_id>',
    slots: [
      {
        name: 'playlist_id',
        description: '播放列表 ID。在播放列表，点击右上角，选择分享播放列表并拷贝，URL 中 pl. 后面的便是播放列表 ID',
        placeholder: 'u-xlyNEdkuoB7rMak',
      },
    ],
    examples: ['music://music.apple.com/library/playlist/pl.u-xlyNEdkuoB7rMak'],
  },
  {
    id: 'ios-apple-music-album',
    name: 'Apple Music 指定专辑',
    description: '打开 Apple Music 指定专辑',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/library/album/<album_id>',
    slots: [
      {
        name: 'album_id',
        description: '专辑 ID。在专辑，点击右上角，选择分享专辑并拷贝，复制的 URL 末尾便是专辑 ID',
        placeholder: '1746665028',
      },
    ],
    examples: ['music://music.apple.com/library/album/1746665028'],
  },
  {
    id: 'ios-apple-music-artist',
    name: 'Apple Music 指定艺人',
    description: '打开 Apple Music 指定艺人',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/library/artist/<artist_id>',
    slots: [
      {
        name: 'artist_id',
        description: '艺人 ID。在艺人，点击右上角，选择分享艺人并拷贝，复制的 URL 末尾便是艺人 ID',
        placeholder: '394019554',
      },
    ],
    examples: ['music://music.apple.com/library/artist/394019554'],
  },
  {
    id: 'ios-apple-music-individual',
    name: 'Apple Music 个人订阅',
    description: '打开 Apple Music 个人订阅',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/subscribe/individual',
    examples: ['music://music.apple.com/subscribe/individual'],
  },
  {
    id: 'ios-apple-music-student',
    name: 'Apple Music 学生订阅',
    description: '打开 Apple Music 学生订阅',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/subscribe/student',
    examples: ['music://music.apple.com/subscribe/student'],
  },
  {
    id: 'ios-apple-music-family',
    name: 'Apple Music 家庭订阅',
    description: '打开 Apple Music 家庭订阅',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/subscribe/family',
    examples: ['music://music.apple.com/subscribe/family'],
  },
  {
    id: 'ios-apple-music-renew',
    name: 'Apple Music 续费',
    description: '打开 Apple Music 续费',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'music://music.apple.com/musicrenew',
    examples: ['music://music.apple.com/musicrenew'],
  },
  {
    id: 'ios-app-store',
    name: 'App Store',
    description: '打开 App Store（仍可用，但加载较慢，更建议使用 Tab 的 URL Scheme）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com',
    examples: ['itms-apps://itunes.apple.com'],
    deprecated: true,
  },
  {
    id: 'ios-app-store-today',
    name: 'App Store Today',
    description: '打开 App Store Today Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/today',
    examples: ['itms-apps://itunes.apple.com/today'],
  },
  {
    id: 'ios-app-store-games',
    name: 'App Store 游戏',
    description: '打开 App Store 游戏 Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/games',
    examples: ['itms-apps://itunes.apple.com/games'],
  },
  {
    id: 'ios-app-store-apps',
    name: 'App Store Apps',
    description: '打开 App Store App Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/apps',
    examples: ['itms-apps://itunes.apple.com/apps'],
  },
  {
    id: 'ios-app-store-arcade',
    name: 'App Store Arcade',
    description: '打开 App Store Arcade Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/arcade',
    examples: ['itms-apps://itunes.apple.com/arcade'],
  },
  {
    id: 'ios-app-store-search',
    name: 'App Store 搜索',
    description: '打开 App Store Search Tab 页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/search',
    examples: ['App-Prefs:root=General'],
  },
  {
    id: 'ios-app-store-search',
    name: 'App Store 搜索内容',
    description: '打开 App Store 搜索并搜索指定内容',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/search?term=<keyword>',
    slots: [
      {
        name: 'keyword',
        description:
          '搜索关键词，更多参数参考：https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/Searching.html#//apple_ref/doc/uid/TP40017632-CH5-SW1',
        placeholder: 'wechat',
      },
    ],
    examples: ['itms-apps://itunes.apple.com/search?term=抖音'],
  },
  {
    id: 'ios-app-store-specific-app',
    name: 'App Store 指定应用',
    description: '打开 App Store 指定应用',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/<region>/app/<bundle_id>/id<apple_id>',
    slots: [
      {
        name: 'region',
        description:
          '国家或地区，如国区 cn、美区 us 等，可参考 https://www.wikiwand.com/en/articles/ISO_3166-1_alpha-2',
        placeholder: 'cn',
      },
      {
        name: 'bundle_id',
        description: '应用 Bundle ID，可在 App Store Connect 中查看',
        placeholder: 'wechat',
      },
      {
        name: 'apple_id',
        description: 'Apple 分配的应用 ID，可在 App Store Connect 中查看',
        placeholder: '414478124',
      },
    ],
    examples: ['itms-apps://itunes.apple.com/cn/app/wechat/id414478124'],
  },
  {
    id: 'ios-app-store-updates',
    name: 'App Store 更新',
    description: '打开 App Store 更新（账户）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/updates',
    examples: ['itms-apps://itunes.apple.com/updates'],
  },
  {
    id: 'ios-itms-ui',
    name: 'App Store 账户设置',
    description: '打开 App Store 账户设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'itms-ui://',
    examples: ['itms-ui://'],
  },
  {
    id: 'ios-apple-store',
    name: 'Apple Store',
    description: '打开 Apple Store',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-09T00:00:00Z',
    urlTemplate: 'applestore://',
    examples: ['applestore://'],
  },
  // TODO: 以下很多设置 URL Scheme 在 iOS 18 上已失效
  // {
  //   id: 'ios-test',
  //   name: '测试',
  //   description: '测试',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'App-Prefs:root=General',
  //   examples: ['App-Prefs:root=General'],
  // },
  // {
  //   id: 'ios-settings-general',
  //   name: '通用设置',
  //   description: '打开 iOS 通用设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'App-Prefs:root=General',
  //   examples: ['App-Prefs:root=General'],
  // },
  // {
  //   id: 'ios-settings-accessibility',
  //   name: '辅助功能',
  //   description: '打开辅助功能设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=ACCESSIBILITY',
  //   examples: ['Prefs:root=General&path=ACCESSIBILITY'],
  // },
  // {
  //   id: 'ios-settings-about',
  //   name: '关于本机',
  //   description: '打开关于本机页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=About',
  //   examples: ['Prefs:root=General&path=About'],
  // },
  // {
  //   id: 'ios-settings-keyboard',
  //   name: '键盘设置',
  //   description: '打开键盘设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Keyboard',
  //   examples: ['Prefs:root=General&path=Keyboard'],
  // },
  // {
  //   id: 'ios-settings-keyboards',
  //   name: '键盘设置 → 键盘',
  //   description: '打开键盘设置中的“键盘”页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Keyboard/KEYBOARDS',
  //   examples: ['Prefs:root=General&path=Keyboard/KEYBOARDS'],
  // },
  // {
  //   id: 'ios-settings-storage',
  //   name: '存储空间',
  //   description: '打开存储空间页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=STORAGE_ICLOUD_USAGE/DEVICE_STORAGE',
  //   examples: ['Prefs:root=General&path=STORAGE_ICLOUD_USAGE/DEVICE_STORAGE'],
  // },
  // {
  //   id: 'ios-settings-profile',
  //   name: '描述文件',
  //   description: '打开描述文件页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=ManagedConfigurationList',
  //   examples: ['Prefs:root=General&path=ManagedConfigurationList'],
  // },
  // {
  //   id: 'ios-settings-date-time',
  //   name: '日期与时间',
  //   description: '打开日期与时间设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=DATE_AND_TIME',
  //   examples: ['Prefs:root=General&path=DATE_AND_TIME'],
  // },
  // {
  //   id: 'ios-settings-language-region',
  //   name: '语言与地区',
  //   description: '打开语言与地区设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=INTERNATIONAL',
  //   examples: ['Prefs:root=General&path=INTERNATIONAL'],
  // },
  // {
  //   id: 'ios-settings-reset',
  //   name: '还原',
  //   description: '打开还原设置页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Reset',
  //   examples: ['Prefs:root=General&path=Reset'],
  // },
  // {
  //   id: 'ios-settings-autolock',
  //   name: '自动锁定时间',
  //   description: '打开自动锁定时间设置页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=AUTOLOCK',
  //   examples: ['Prefs:root=General&path=AUTOLOCK'],
  // },
  // {
  //   id: 'ios-settings-privacy',
  //   name: '隐私设置',
  //   description: '打开隐私设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Privacy',
  //   examples: ['Prefs:root=Privacy'],
  // },
  // {
  //   id: 'ios-settings-privacy-location',
  //   name: '定位服务',
  //   description: '打开隐私设置中的定位服务',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Privacy&path=LOCATION',
  //   examples: ['Prefs:root=Privacy&path=LOCATION'],
  // },
  // {
  //   id: 'ios-settings-battery',
  //   name: '电池电量',
  //   description: '打开电池电量设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=BATTERY_USAGE',
  //   examples: ['Prefs:root=BATTERY_USAGE'],
  // },
  // {
  //   id: 'ios-settings-cellular',
  //   name: '蜂窝数据',
  //   description: '打开蜂窝数据设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=MOBILE_DATA_SETTINGS_ID',
  //   examples: ['Prefs:root=MOBILE_DATA_SETTINGS_ID'],
  // },
  // {
  //   id: 'ios-settings-bluetooth',
  //   name: '蓝牙设置',
  //   description: '打开蓝牙设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Bluetooth',
  //   examples: ['Prefs:root=Bluetooth'],
  // },
  // {
  //   id: 'ios-settings-display',
  //   name: '显示设置',
  //   description: '打开显示设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=DISPLAY',
  //   examples: ['Prefs:root=DISPLAY'],
  // },
  // {
  //   id: 'ios-settings-sounds',
  //   name: '声音设置',
  //   description: '打开声音设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Sounds',
  //   examples: ['Prefs:root=Sounds'],
  // },
  // {
  //   id: 'ios-settings-ringtone',
  //   name: '铃声设置',
  //   description: '打开铃声设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Sounds&path=Ringtone',
  //   examples: ['Prefs:root=Sounds&path=Ringtone'],
  // },
  // {
  //   id: 'ios-settings-wallpaper',
  //   name: '墙纸设置',
  //   description: '打开墙纸设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Wallpaper',
  //   examples: ['Prefs:root=Wallpaper'],
  // },
  // {
  //   id: 'ios-settings-hotspot',
  //   name: '个人热点',
  //   description: '打开个人热点设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=INTERNET_TETHERING',
  //   examples: ['Prefs:root=INTERNET_TETHERING'],
  // },
  // {
  //   id: 'ios-settings-airplane',
  //   name: '飞行模式',
  //   description: '打开飞行模式设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=AIRPLANE_MODE',
  //   examples: ['Prefs:root=AIRPLANE_MODE'],
  // },
  // {
  //   id: 'ios-settings-mail',
  //   name: '邮件设置',
  //   description: '打开邮件设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=ACCOUNT_SETTINGS',
  //   examples: ['Prefs:root=ACCOUNT_SETTINGS'],
  // },
  // {
  //   id: 'ios-settings-facetime',
  //   name: 'FaceTime 设置',
  //   description: '打开 FaceTime 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=FACETIME',
  //   examples: ['Prefs:root=FACETIME'],
  // },
  // {
  //   id: 'ios-settings-music',
  //   name: '音乐设置',
  //   description: '打开音乐设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=MUSIC',
  //   examples: ['Prefs:root=MUSIC'],
  // },
  // {
  //   id: 'ios-settings-notes',
  //   name: '备忘录设置',
  //   description: '打开备忘录设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=NOTES',
  //   examples: ['Prefs:root=NOTES'],
  // },
  // {
  //   id: 'ios-settings-notifications',
  //   name: '通知设置',
  //   description: '打开通知设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=NOTIFICATIONS_ID',
  //   examples: ['Prefs:root=NOTIFICATIONS_ID'],
  // },
  // {
  //   id: 'ios-settings-touchid',
  //   name: '指纹/面容与密码',
  //   description: '打开指纹/面容与密码设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=TOUCHID_PASSCODE',
  //   examples: ['Prefs:root=TOUCHID_PASSCODE'],
  // },
  // {
  //   id: 'ios-settings-wallet',
  //   name: '钱包与 Apple Pay',
  //   description: '打开钱包与 Apple Pay 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=PASSBOOK',
  //   examples: ['Prefs:root=PASSBOOK'],
  // },
  // {
  //   id: 'ios-settings-phone',
  //   name: '电话设置',
  //   description: '打开电话设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Phone',
  //   examples: ['Prefs:root=Phone'],
  // },
  // {
  //   id: 'ios-settings-photos',
  //   name: '照片设置',
  //   description: '打开照片设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Photos',
  //   examples: ['Prefs:root=Photos'],
  // },
  // {
  //   id: 'ios-settings-siri',
  //   name: 'Siri 设置',
  //   description: '打开 Siri 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=SIRI',
  //   examples: ['Prefs:root=SIRI'],
  // },
  // {
  //   id: 'ios-settings-wifi',
  //   name: '无线局域网设置',
  //   description: '打开 Wi-Fi 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=WIFI',
  //   examples: ['Prefs:root=WIFI'],
  // },
  // {
  //   id: 'ios-settings-icloud',
  //   name: 'iCloud 设置',
  //   description: '打开 iCloud 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=CASTLE',
  //   examples: ['Prefs:root=CASTLE'],
  // },
  // {
  //   id: 'ios-settings-appstore',
  //   name: 'App Store 设置',
  //   description: '打开 App Store 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=STORE',
  //   examples: ['Prefs:root=STORE'],
  // },
  // {
  //   id: 'ios-settings-control-center',
  //   name: '自定控制中心',
  //   description: '打开控制中心自定页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=ControlCenter&path=CUSTOMIZE_CONTROLS',
  //   examples: ['Prefs:root=ControlCenter&path=CUSTOMIZE_CONTROLS'],
  // },

  // // iOS 系统应用相关 URL Scheme
  // {
  //   id: 'ios-wallet',
  //   name: 'iOS 钱包',
  //   description: '打开 iOS 钱包',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'shoebox://url-scheme',
  //   examples: ['shoebox://url-scheme'],
  // },
  // {
  //   id: 'ios-safari',
  //   name: 'Safari 浏览器',
  //   description: '打开 Safari 浏览器',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'x-web-search://',
  //   examples: ['x-web-search://'],
  // },
  // {
  //   id: 'ios-shortcut',
  //   name: '捷径（旧版）',
  //   description: '运行捷径（旧版）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'workflow://run-workflow?name=<name>&input=<input>',
  //   slots: [
  //     {
  //       name: 'name',
  //       description: '捷径名称',
  //       placeholder: '我的捷径',
  //     },
  //     {
  //       name: 'input',
  //       description: '输入内容',
  //       placeholder: 'Hello World',
  //     },
  //   ],
  //   examples: ['workflow://run-workflow?name=我的捷径&input=Hello%20World'],
  // },
  // {
  //   id: 'ios-maps',
  //   name: '地图',
  //   description: '打开地图',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'map://',
  //   examples: ['map://'],
  // },
  // {
  //   id: 'ios-clock-worldclock',
  //   name: '世界时钟',
  //   description: '打开世界时钟',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-worldclock://',
  //   examples: ['Clock-worldclock://'],
  // },
  // {
  //   id: 'ios-clock-alarm',
  //   name: '闹钟',
  //   description: '打开闹钟',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-alarm://',
  //   examples: ['Clock-alarm://'],
  // },
  // {
  //   id: 'ios-clock-stopwatch',
  //   name: '秒表',
  //   description: '打开秒表',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-stopwatch://',
  //   examples: ['Clock-stopwatch://'],
  // },
  // {
  //   id: 'ios-clock-timer',
  //   name: '倒计时',
  //   description: '打开倒计时',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-timer://',
  //   examples: ['Clock-timer://'],
  // },
  // {
  //   id: 'ios-photos',
  //   name: '相册',
  //   description: '打开相册',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Photos://',
  //   examples: ['Photos://'],
  // },
  // {
  //   id: 'ios-find-iphone',
  //   name: '查找 iPhone',
  //   description: '打开查找 iPhone',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'fmip1://',
  //   examples: ['fmip1://'],
  // },
  // {
  //   id: 'ios-tel',
  //   name: '打电话',
  //   description: '拨打电话',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'tel://<number>',
  //   slots: [
  //     {
  //       name: 'number',
  //       description: '电话号码',
  //       placeholder: '110',
  //     },
  //   ],
  //   examples: ['tel://110'],
  // },
  // {
  //   id: 'ios-sms',
  //   name: '发送短信',
  //   description: '给指定号码发送短信',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'sms://<number>',
  //   slots: [
  //     {
  //       name: 'number',
  //       description: '手机号码',
  //       placeholder: '13812345678',
  //     },
  //   ],
  //   examples: ['sms://13812345678'],
  // },
  // {
  //   id: 'ios-notes',
  //   name: '备忘录',
  //   description: '打开备忘录',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'mobilenotes://',
  //   examples: ['mobilenotes://'],
  // },
  // {
  //   id: 'ios-calendar',
  //   name: '日历',
  //   description: '打开日历',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'calshow://',
  //   examples: ['calshow://'],
  // },
]

export default IOS
