import type { UrlSchemeWithoutCategory } from '@/types'

const IOS: UrlSchemeWithoutCategory[] = [
  // TODO: 加载点慢，而且不是首页 Tab
  {
    id: 'ios-app-store',
    name: 'App Store',
    description: '打开 App Store',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'itms-apps://itunes.apple.com/cn',
    examples: ['itms-apps://itunes.apple.com'],
  },
  {
    id: 'ios-music-show-now-playing',
    name: 'Apple Music 播放页',
    description: '打开 Apple Music 播放页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'music://shownowplaying',
    examples: ['music://shownowplaying'],
  },
  {
    id: 'ios-music-search',
    name: 'Apple Music 搜索',
    description: '打开 Apple Music 搜索',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-08T00:00:00Z',
    urlTemplate: 'music://music.apple.com/search',
    examples: ['music://music.apple.com/search'],
  },
  // TODO: 以下很多设置 URL Scheme 在 iOS 18 上已失效
  // {
  //   id: 'ios-test',
  //   name: '测试',
  //   description: '测试',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'App-Prefs:root=General',
  //   examples: ['App-Prefs:root=General'],
  // },
  // {
  //   id: 'ios-settings-general',
  //   name: '通用设置',
  //   description: '打开 iOS 通用设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'App-Prefs:root=General',
  //   examples: ['App-Prefs:root=General'],
  // },
  // {
  //   id: 'ios-settings-accessibility',
  //   name: '辅助功能',
  //   description: '打开辅助功能设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=ACCESSIBILITY',
  //   examples: ['Prefs:root=General&path=ACCESSIBILITY'],
  // },
  // {
  //   id: 'ios-settings-about',
  //   name: '关于本机',
  //   description: '打开关于本机页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=About',
  //   examples: ['Prefs:root=General&path=About'],
  // },
  // {
  //   id: 'ios-settings-keyboard',
  //   name: '键盘设置',
  //   description: '打开键盘设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Keyboard',
  //   examples: ['Prefs:root=General&path=Keyboard'],
  // },
  // {
  //   id: 'ios-settings-keyboards',
  //   name: '键盘设置 → 键盘',
  //   description: '打开键盘设置中的“键盘”页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Keyboard/KEYBOARDS',
  //   examples: ['Prefs:root=General&path=Keyboard/KEYBOARDS'],
  // },
  // {
  //   id: 'ios-settings-storage',
  //   name: '存储空间',
  //   description: '打开存储空间页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=STORAGE_ICLOUD_USAGE/DEVICE_STORAGE',
  //   examples: ['Prefs:root=General&path=STORAGE_ICLOUD_USAGE/DEVICE_STORAGE'],
  // },
  // {
  //   id: 'ios-settings-profile',
  //   name: '描述文件',
  //   description: '打开描述文件页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=ManagedConfigurationList',
  //   examples: ['Prefs:root=General&path=ManagedConfigurationList'],
  // },
  // {
  //   id: 'ios-settings-date-time',
  //   name: '日期与时间',
  //   description: '打开日期与时间设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=DATE_AND_TIME',
  //   examples: ['Prefs:root=General&path=DATE_AND_TIME'],
  // },
  // {
  //   id: 'ios-settings-language-region',
  //   name: '语言与地区',
  //   description: '打开语言与地区设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=INTERNATIONAL',
  //   examples: ['Prefs:root=General&path=INTERNATIONAL'],
  // },
  // {
  //   id: 'ios-settings-reset',
  //   name: '还原',
  //   description: '打开还原设置页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=Reset',
  //   examples: ['Prefs:root=General&path=Reset'],
  // },
  // {
  //   id: 'ios-settings-autolock',
  //   name: '自动锁定时间',
  //   description: '打开自动锁定时间设置页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=General&path=AUTOLOCK',
  //   examples: ['Prefs:root=General&path=AUTOLOCK'],
  // },
  // {
  //   id: 'ios-settings-privacy',
  //   name: '隐私设置',
  //   description: '打开隐私设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Privacy',
  //   examples: ['Prefs:root=Privacy'],
  // },
  // {
  //   id: 'ios-settings-privacy-location',
  //   name: '定位服务',
  //   description: '打开隐私设置中的定位服务',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Privacy&path=LOCATION',
  //   examples: ['Prefs:root=Privacy&path=LOCATION'],
  // },
  // {
  //   id: 'ios-settings-battery',
  //   name: '电池电量',
  //   description: '打开电池电量设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=BATTERY_USAGE',
  //   examples: ['Prefs:root=BATTERY_USAGE'],
  // },
  // {
  //   id: 'ios-settings-cellular',
  //   name: '蜂窝数据',
  //   description: '打开蜂窝数据设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=MOBILE_DATA_SETTINGS_ID',
  //   examples: ['Prefs:root=MOBILE_DATA_SETTINGS_ID'],
  // },
  // {
  //   id: 'ios-settings-bluetooth',
  //   name: '蓝牙设置',
  //   description: '打开蓝牙设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Bluetooth',
  //   examples: ['Prefs:root=Bluetooth'],
  // },
  // {
  //   id: 'ios-settings-display',
  //   name: '显示设置',
  //   description: '打开显示设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=DISPLAY',
  //   examples: ['Prefs:root=DISPLAY'],
  // },
  // {
  //   id: 'ios-settings-sounds',
  //   name: '声音设置',
  //   description: '打开声音设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Sounds',
  //   examples: ['Prefs:root=Sounds'],
  // },
  // {
  //   id: 'ios-settings-ringtone',
  //   name: '铃声设置',
  //   description: '打开铃声设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Sounds&path=Ringtone',
  //   examples: ['Prefs:root=Sounds&path=Ringtone'],
  // },
  // {
  //   id: 'ios-settings-wallpaper',
  //   name: '墙纸设置',
  //   description: '打开墙纸设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Wallpaper',
  //   examples: ['Prefs:root=Wallpaper'],
  // },
  // {
  //   id: 'ios-settings-hotspot',
  //   name: '个人热点',
  //   description: '打开个人热点设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=INTERNET_TETHERING',
  //   examples: ['Prefs:root=INTERNET_TETHERING'],
  // },
  // {
  //   id: 'ios-settings-airplane',
  //   name: '飞行模式',
  //   description: '打开飞行模式设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=AIRPLANE_MODE',
  //   examples: ['Prefs:root=AIRPLANE_MODE'],
  // },
  // {
  //   id: 'ios-settings-mail',
  //   name: '邮件设置',
  //   description: '打开邮件设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=ACCOUNT_SETTINGS',
  //   examples: ['Prefs:root=ACCOUNT_SETTINGS'],
  // },
  // {
  //   id: 'ios-settings-facetime',
  //   name: 'FaceTime 设置',
  //   description: '打开 FaceTime 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=FACETIME',
  //   examples: ['Prefs:root=FACETIME'],
  // },
  // {
  //   id: 'ios-settings-music',
  //   name: '音乐设置',
  //   description: '打开音乐设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=MUSIC',
  //   examples: ['Prefs:root=MUSIC'],
  // },
  // {
  //   id: 'ios-settings-notes',
  //   name: '备忘录设置',
  //   description: '打开备忘录设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=NOTES',
  //   examples: ['Prefs:root=NOTES'],
  // },
  // {
  //   id: 'ios-settings-notifications',
  //   name: '通知设置',
  //   description: '打开通知设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=NOTIFICATIONS_ID',
  //   examples: ['Prefs:root=NOTIFICATIONS_ID'],
  // },
  // {
  //   id: 'ios-settings-touchid',
  //   name: '指纹/面容与密码',
  //   description: '打开指纹/面容与密码设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=TOUCHID_PASSCODE',
  //   examples: ['Prefs:root=TOUCHID_PASSCODE'],
  // },
  // {
  //   id: 'ios-settings-wallet',
  //   name: '钱包与 Apple Pay',
  //   description: '打开钱包与 Apple Pay 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=PASSBOOK',
  //   examples: ['Prefs:root=PASSBOOK'],
  // },
  // {
  //   id: 'ios-settings-phone',
  //   name: '电话设置',
  //   description: '打开电话设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Phone',
  //   examples: ['Prefs:root=Phone'],
  // },
  // {
  //   id: 'ios-settings-photos',
  //   name: '照片设置',
  //   description: '打开照片设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=Photos',
  //   examples: ['Prefs:root=Photos'],
  // },
  // {
  //   id: 'ios-settings-siri',
  //   name: 'Siri 设置',
  //   description: '打开 Siri 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=SIRI',
  //   examples: ['Prefs:root=SIRI'],
  // },
  // {
  //   id: 'ios-settings-wifi',
  //   name: '无线局域网设置',
  //   description: '打开 Wi-Fi 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=WIFI',
  //   examples: ['Prefs:root=WIFI'],
  // },
  // {
  //   id: 'ios-settings-icloud',
  //   name: 'iCloud 设置',
  //   description: '打开 iCloud 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=CASTLE',
  //   examples: ['Prefs:root=CASTLE'],
  // },
  // {
  //   id: 'ios-settings-appstore',
  //   name: 'App Store 设置',
  //   description: '打开 App Store 设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=STORE',
  //   examples: ['Prefs:root=STORE'],
  // },
  // {
  //   id: 'ios-settings-control-center',
  //   name: '自定控制中心',
  //   description: '打开控制中心自定页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Prefs:root=ControlCenter&path=CUSTOMIZE_CONTROLS',
  //   examples: ['Prefs:root=ControlCenter&path=CUSTOMIZE_CONTROLS'],
  // },

  // // iOS 系统应用相关 URL Scheme
  // {
  //   id: 'ios-wallet',
  //   name: 'iOS 钱包',
  //   description: '打开 iOS 钱包',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'shoebox://url-scheme',
  //   examples: ['shoebox://url-scheme'],
  // },
  // {
  //   id: 'ios-safari',
  //   name: 'Safari 浏览器',
  //   description: '打开 Safari 浏览器',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'x-web-search://',
  //   examples: ['x-web-search://'],
  // },
  // {
  //   id: 'ios-shortcut',
  //   name: '捷径（旧版）',
  //   description: '运行捷径（旧版）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'workflow://run-workflow?name=<name>&input=<input>',
  //   slots: [
  //     {
  //       name: 'name',
  //       description: '捷径名称',
  //       placeholder: '我的捷径',
  //     },
  //     {
  //       name: 'input',
  //       description: '输入内容',
  //       placeholder: 'Hello World',
  //     },
  //   ],
  //   examples: ['workflow://run-workflow?name=我的捷径&input=Hello%20World'],
  // },
  // {
  //   id: 'ios-maps',
  //   name: '地图',
  //   description: '打开地图',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'map://',
  //   examples: ['map://'],
  // },
  // {
  //   id: 'ios-clock-worldclock',
  //   name: '世界时钟',
  //   description: '打开世界时钟',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-worldclock://',
  //   examples: ['Clock-worldclock://'],
  // },
  // {
  //   id: 'ios-clock-alarm',
  //   name: '闹钟',
  //   description: '打开闹钟',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-alarm://',
  //   examples: ['Clock-alarm://'],
  // },
  // {
  //   id: 'ios-clock-stopwatch',
  //   name: '秒表',
  //   description: '打开秒表',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-stopwatch://',
  //   examples: ['Clock-stopwatch://'],
  // },
  // {
  //   id: 'ios-clock-timer',
  //   name: '倒计时',
  //   description: '打开倒计时',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Clock-timer://',
  //   examples: ['Clock-timer://'],
  // },
  // {
  //   id: 'ios-photos',
  //   name: '相册',
  //   description: '打开相册',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'Photos://',
  //   examples: ['Photos://'],
  // },
  // {
  //   id: 'ios-find-iphone',
  //   name: '查找 iPhone',
  //   description: '打开查找 iPhone',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'fmip1://',
  //   examples: ['fmip1://'],
  // },
  // {
  //   id: 'ios-tel',
  //   name: '打电话',
  //   description: '拨打电话',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'tel://<number>',
  //   slots: [
  //     {
  //       name: 'number',
  //       description: '电话号码',
  //       placeholder: '110',
  //     },
  //   ],
  //   examples: ['tel://110'],
  // },
  // {
  //   id: 'ios-sms',
  //   name: '发送短信',
  //   description: '给指定号码发送短信',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'sms://<number>',
  //   slots: [
  //     {
  //       name: 'number',
  //       description: '手机号码',
  //       placeholder: '13812345678',
  //     },
  //   ],
  //   examples: ['sms://13812345678'],
  // },
  // {
  //   id: 'ios-notes',
  //   name: '备忘录',
  //   description: '打开备忘录',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'mobilenotes://',
  //   examples: ['mobilenotes://'],
  // },
  // {
  //   id: 'ios-calendar',
  //   name: '日历',
  //   description: '打开日历',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-08T00:00:00Z',
  //   urlTemplate: 'calshow://',
  //   examples: ['calshow://'],
  // },
]

export default IOS
