import type { UrlSchemeWithoutCategory } from '@/types'

const MEITUAN: UrlSchemeWithoutCategory[] = [
  {
    id: 'meituan_home',
    name: '首页',
    description: '打开美团首页 Tab',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/home',
    examples: ['imeituan://www.meituan.com/home'],
  },
  {
    id: 'meituan_message_center',
    name: '消息',
    description: '打开美团消息 Tab',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/messagecenter',
    examples: ['imeituan://www.meituan.com/messagecenter'],
  },
  {
    id: 'meituan_tabshoppingcart',
    name: '购物车',
    description: '打开美团购物车 Tab',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/tabshoppingcart',
    examples: ['imeituan://www.meituan.com/tabshoppingcart'],
  },
  {
    id: 'meituan_user',
    name: '我的',
    description: '打开美团我的 Tab',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/user',
    examples: ['imeituan://www.meituan.com/user'],
  },
  {
    id: 'meituan_morecates',
    name: '更多服务',
    description: '打开美团首页更多服务',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/morecates',
    examples: ['imeituan://www.meituan.com/morecates'],
  },
  {
    id: 'meituan_hotel_homepage',
    name: '酒店民宿',
    description: '打开美团酒店民宿服务',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/hotel/homepage',
    examples: ['imeituan://www.meituan.com/hotel/homepage'],
  },
  {
    id: 'meituan_hotel_search_input',
    name: '搜索酒店民宿',
    description: '打开美团搜索酒店民宿',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    // imeituan://www.meituan.com/hotel/search
    // imeituan://www.meituan.com/hotel/search/input?fromfront=true&amp;ishour=true&amp;searchResult=false&amp;fromFlight=false&amp;city_id=1&amp;areaId=0&amp;areaType=10&amp;cate=20&amp;sort=defaults&amp;sourceType=hote
    urlSchemeTemplate: 'imeituan://www.meituan.com/hotel/search/input',
    examples: ['imeituan://www.meituan.com/hotel/search/input'],
  },
  {
    id: 'meituan_overseas_hotel_search',
    name: '搜索酒店民宿（海外）',
    description: '打开美团搜索海外酒店民宿',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-28T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/overseahotel/search',
    examples: ['imeituan://www.meituan.com/overseahotel/search'],
  },
  {
    id: 'meituan_mrn_zhenguo_product',
    name: '预订酒店民宿',
    description: '打开美团指定酒店民宿房源详情（预订）',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate:
      'imeituan://www.meituan.com/mrn?productId={product_id}&startDate={startDate}&endDate={endDate}&bizType=0&mrn_biz=zhenguo&mrn_entry=product&mrn_component=zhenguo-product',
    slots: [
      {
        name: 'product_id',
        description: '酒店民宿 ID。进入房源分享复制链接，在浏览器打开从 URL 上获取 productId',
        placeholder: '15651180',
      },
      {
        name: 'startDate',
        description: '入住日期（可选）',
        placeholder: '20250826',
      },
      {
        name: 'endDate',
        description: '退房日期（可选）',
        placeholder: '20250830',
      },
    ],
    examples: [
      'imeituan://www.meituan.com/mrn?productId=15651180&bizType=0&mrn_biz=zhenguo&mrn_entry=product&mrn_component=zhenguo-product',
      'imeituan://www.meituan.com/mrn?productId=15651180&startDate=20250826&endDate=20250830&bizType=0&mrn_biz=zhenguo&mrn_entry=product&mrn_component=zhenguo-product',
    ],
  },
  {
    id: 'meituan_food_homepage',
    name: '美食',
    description: '打开美团美食服务',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-28T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/food/homepage',
    examples: ['imeituan://www.meituan.com/food/homepage'],
  },
  {
    id: 'meituan_food_mrn',
    name: '美食店铺',
    description: '打开美食店铺详情',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-28T00:00:00Z',
    urlSchemeTemplate:
      'imeituan://www.meituan.com/mrn?mrn_biz=meishi&mrn_entry=food-poi&mrn_component=food-poi&poiId={poi_id}',
    slots: [
      {
        name: 'poi_id',
        description:
          'POI ID（Point of interest）是美团给商家门店设置的唯一 ID。在店铺选择分享，复制链接到浏览器打开，在地址栏可获取 poiId。',
        placeholder: '1180935216',
      },
    ],
    examples: [
      'imeituan://www.meituan.com/mrn?mrn_biz=meishi&mrn_entry=food-poi&mrn_component=food-poi&poiId=1180935216',
    ],
  },
  {
    id: 'meituan_travel_poi',
    name: '景点详情',
    description: '打开美团指定景点详情',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-28T00:00:00Z',
    urlSchemeTemplate: 'imeituan://www.meituan.com/travel/poi?id={poi_id}',
    slots: [
      {
        name: 'poi_id',
        description: '景点 ID。在景点选择分享，复制链接到浏览器打开，在地址栏可获取 poiId。',
        placeholder: '271772',
      },
    ],
    examples: ['imeituan://www.meituan.com/travel/poi?id=271772'],
  },
  {
    id: 'meituan_wallet_launch',
    name: '美团钱包',
    description: '打开美团钱包',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-26T00:00:00Z',
    urlSchemeTemplate: 'imeituan://wallet/launch',
    examples: ['imeituan://wallet/launch'],
  },
  // TODO: 待验证
  // {
  //   id: 'meituan_mtp_order_buy',
  //   name: '门票购买',
  //   description: '打开门票购买页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/mtp/order/buy',
  //   examples: ['imeituan://www.meituan.com/mtp/order/buy'],
  // },
  // {
  //   id: 'meituan_travel_web',
  //   name: '旅游网页',
  //   description: '打开旅游网页',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/travel/web',
  //   examples: ['imeituan://www.meituan.com/travel/web'],
  // },
  // {
  //   id: 'meituan_travel_china_homepage',
  //   name: '国内旅游首页',
  //   description: '打开国内旅游首页',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/travel/china/homepage',
  //   examples: ['imeituan://www.meituan.com/travel/china/homepage'],
  // },
  // {
  //   id: 'meituan_overseas_city_portal',
  //   name: '海外城市门户',
  //   description: '打开海外城市门户页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/overseas/cityportal',
  //   examples: ['imeituan://www.meituan.com/overseas/cityportal'],
  // },

  // // 内容相关
  // {
  //   id: 'meituan_novel_reader',
  //   name: '小说阅读器',
  //   description: '打开小说阅读器',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/novel/reader',
  //   examples: ['imeituan://www.meituan.com/novel/reader'],
  // },
  // {
  //   id: 'meituan_novel_audio',
  //   name: '小说音频',
  //   description: '打开小说音频页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/novel/audio',
  //   examples: ['imeituan://www.meituan.com/novel/audio'],
  // },
  // {
  //   id: 'meituan_novel_video',
  //   name: '小说视频',
  //   description: '打开小说视频页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/novel/video',
  //   examples: ['imeituan://www.meituan.com/novel/video'],
  // },
  // {
  //   id: 'meituan_novel_landscape',
  //   name: '小说横屏',
  //   description: '打开小说横屏页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/novel/landscape',
  //   examples: ['imeituan://www.meituan.com/novel/landscape'],
  // },
  // {
  //   id: 'meituan_feed_detail',
  //   name: 'Feed 详情',
  //   description: '打开 Feed 详情页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/feed/detail',
  //   examples: ['imeituan://www.meituan.com/feed/detail'],
  // },
  // {
  //   id: 'meituan_review_list',
  //   name: '评价列表',
  //   description: '打开评价列表页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/reviewlist',
  //   examples: ['imeituan://www.meituan.com/reviewlist'],
  // },
  // {
  //   id: 'meituan_content_recommend_video',
  //   name: '内容推荐视频',
  //   description: '打开内容推荐视频页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/content/recommend/video',
  //   examples: ['imeituan://www.meituan.com/content/recommend/video'],
  // },

  // // 系统功能
  // {
  //   id: 'meituan_tfkit_show',
  //   name: '升级对话框',
  //   description: '显示升级对话框',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/tfkit/show',
  //   examples: ['imeituan://www.meituan.com/tfkit/show'],
  // },
  // {
  //   id: 'meituan_permission_dialog',
  //   name: '权限对话框',
  //   description: '显示权限对话框',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/permission/dialog',
  //   examples: ['imeituan://www.meituan.com/permission/dialog'],
  // },
  // {
  //   id: 'meituan_appguard_dialog',
  //   name: '应用保护对话框',
  //   description: '显示应用保护对话框',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/appguard/dialog',
  //   examples: ['imeituan://www.meituan.com/appguard/dialog'],
  // },
  // {
  //   id: 'meituan_voip_callkf',
  //   name: '客服电话',
  //   description: '拨打客服电话',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'imeituan://www.meituan.com/voip/callkf',
  //   examples: ['imeituan://www.meituan.com/voip/callkf'],
  // },

  // // 大写版本 iMeituan
  // {
  //   id: 'imeituan_feed_detail',
  //   name: 'Feed 详情（大写版）',
  //   description: '打开 Feed 详情页面（大写版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'iMeituan://www.meituan.com/feed/detail',
  //   examples: ['iMeituan://www.meituan.com/feed/detail'],
  // },
  // {
  //   id: 'imeituan_review_list',
  //   name: '评价列表（大写版）',
  //   description: '打开评价列表页面（大写版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'iMeituan://www.meituan.com/reviewlist',
  //   examples: ['iMeituan://www.meituan.com/reviewlist'],
  // },
  // {
  //   id: 'imeituan_hotel_review_list',
  //   name: '酒店评价列表（大写版）',
  //   description: '打开酒店评价列表页面（大写版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'iMeituan://www.meituan.com/hotel/review/list',
  //   examples: ['iMeituan://www.meituan.com/hotel/review/list'],
  // },

  // // meituanpayment 支付相关
  // {
  //   id: 'meituanpayment_auth_verify_voiceprint',
  //   name: '语音验证',
  //   description: '进行语音验证',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://auth/verifyvoiceprint',
  //   examples: ['meituanpayment://auth/verifyvoiceprint'],
  // },
  // {
  //   id: 'meituanpayment_wallet_deduct_pay_list',
  //   name: '代扣支付列表',
  //   description: '打开代扣支付列表页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/paymanagement/deductpaylist',
  //   examples: ['meituanpayment://wallet/paymanagement/deductpaylist'],
  // },
  // {
  //   id: 'meituanpayment_wallet_balance',
  //   name: '账户余额（支付版）',
  //   description: '打开账户余额页面（支付版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/accountbalance',
  //   examples: ['meituanpayment://wallet/accountbalance'],
  // },
  // {
  //   id: 'meituanpayment_wallet_pay_management',
  //   name: '支付管理',
  //   description: '打开支付管理页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/paymanagement',
  //   examples: ['meituanpayment://wallet/paymanagement'],
  // },
  // {
  //   id: 'meituanpayment_wallet_nopassword',
  //   name: '免密管理（支付版）',
  //   description: '打开免密管理页面（支付版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/nopasswordmanagement',
  //   examples: ['meituanpayment://wallet/nopasswordmanagement'],
  // },
  // {
  //   id: 'meituanpayment_wallet_bankcard',
  //   name: '银行卡绑定（支付版）',
  //   description: '打开银行卡绑定页面（支付版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/bankcardbinding',
  //   examples: ['meituanpayment://wallet/bankcardbinding'],
  // },
  // {
  //   id: 'meituanpayment_wallet_bankcard_list',
  //   name: '银行卡列表',
  //   description: '打开银行卡列表页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/bankcardlist',
  //   examples: ['meituanpayment://wallet/bankcardlist'],
  // },
  // {
  //   id: 'meituanpayment_wallet_bankcard_pay_limit',
  //   name: '银行卡支付限额',
  //   description: '打开银行卡支付限额页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/bankcardpayLimit',
  //   examples: ['meituanpayment://wallet/bankcardpayLimit'],
  // },
  // {
  //   id: 'meituanpayment_wallet_launch',
  //   name: '钱包启动（支付版）',
  //   description: '启动钱包（支付版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://wallet/launch',
  //   examples: ['meituanpayment://wallet/launch'],
  // },
  // {
  //   id: 'meituanpayment_picasso_module',
  //   name: '模块视图控制器',
  //   description: '打开模块视图控制器',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://picasso/moduleViewController',
  //   examples: ['meituanpayment://picasso/moduleViewController'],
  // },
  // {
  //   id: 'meituanpayment_halfpage_launch',
  //   name: '半页启动',
  //   description: '启动半页功能',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://halfpage/launch',
  //   examples: ['meituanpayment://halfpage/launch'],
  // },
  // {
  //   id: 'meituanpayment_pay_password_retrieve',
  //   name: '密码找回',
  //   description: '打开密码找回页面',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://pay/password/retrieve',
  //   examples: ['meituanpayment://pay/password/retrieve'],
  // },
  // {
  //   id: 'meituanpayment_web',
  //   name: '网页（支付版）',
  //   description: '打开网页（支付版本）',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://www.meituan.com/web',
  //   examples: ['meituanpayment://www.meituan.com/web'],
  // },
  // {
  //   id: 'meituanpayment_auth_verify_password',
  //   name: '密码验证',
  //   description: '进行密码验证',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://auth/verifypassword',
  //   examples: ['meituanpayment://auth/verifypassword'],
  // },
  // {
  //   id: 'meituanpayment_auth_verify_fingerprint',
  //   name: '指纹验证',
  //   description: '进行指纹验证',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-26T00:00:00Z',
  //   urlSchemeTemplate: 'meituanpayment://auth/verifyfingerprint',
  //   examples: ['meituanpayment://auth/verifyfingerprint'],
  // },
]

export default MEITUAN
