import type { UrlSchemeWithoutCategory } from '@/types'

const WECHAT: UrlSchemeWithoutCategory[] = [
  {
    id: 'wechat_scan',
    name: '扫一扫',
    description: '打开微信扫一扫',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlSchemeTemplate: 'weixin://scanqrcode',
    examples: ['weixin://scanqrcode'],
  },
  {
    id: 'wechat_pay_code',
    name: '收付款',
    description: '打开微信收付款',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlSchemeTemplate: 'weixin://widget/pay',
    examples: ['weixin://widget/pay'],
  },
  {
    id: 'wechat_moments',
    name: '朋友圈',
    description: '打开朋友圈',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/moments',
    examples: ['weixin://dl/moments'],
    deprecated: true,
  },
  {
    id: 'wechat_official_accounts',
    name: '公众号',
    description: '打开微信公众号',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/officialaccounts',
    examples: ['weixin://dl/officialaccounts'],
    deprecated: true,
  },
  {
    id: 'wechat_games',
    name: '游戏',
    description: '打开微信游戏',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/games',
    examples: ['weixin://dl/games'],
    deprecated: true,
  },
  {
    id: 'wechat_profile',
    name: '个人资料',
    description: '打开微信个人资料',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/profile',
    examples: ['weixin://dl/profile'],
    deprecated: true,
  },
  {
    id: 'wechat_settings',
    name: '设置',
    description: '打开微信设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/settings',
    examples: ['weixin://dl/settings'],
    deprecated: true,
  },
  {
    id: 'wechat_settings_general',
    name: '设置-通用',
    description: '打开微信通用设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/general',
    examples: ['weixin://dl/general'],
    deprecated: true,
  },
  {
    id: 'wechat_settings_notifications',
    name: '设置-通知',
    description: '打开微信通知设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/notifications',
    examples: ['weixin://dl/notifications'],
    deprecated: true,
  },
  {
    id: 'wechat_chat_settings',
    name: '聊天设置',
    description: '打开微信聊天设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/chat',
    examples: ['weixin://dl/chat'],
    deprecated: true,
  },
  {
    id: 'wechat_features',
    name: '功能插件',
    description: '打开微信功能插件',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/features',
    examples: ['weixin://dl/features'],
    deprecated: true,
  },
  {
    id: 'wechat_feedback',
    name: '反馈',
    description: '打开微信反馈',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/feedback',
    examples: ['weixin://dl/feedback'],
    deprecated: true,
  },
  {
    id: 'wechat_help',
    name: '帮助',
    description: '打开微信帮助',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-07T00:00:00Z',
    urlSchemeTemplate: 'weixin://dl/help',
    examples: ['weixin://dl/help'],
    deprecated: true,
  },
] as const

export default WECHAT
