import type { UrlSchemeWithoutCategory } from '@/types'

const XIAOHONGSHU: UrlSchemeWithoutCategory[] = [
  {
    id: 'xiaohongshu-scan',
    name: '扫一扫',
    description: '打开扫一扫',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://scan',
    examples: ['xhsdiscover://scan'],
  },
  {
    id: 'xiaohongshu-item-detail',
    name: '图文笔记',
    description: '打开图文笔记详情',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://item/{note_id}',
    slots: [
      {
        name: 'note_id',
        description: '图文笔记 ID',
        placeholder: '6879e557000000000d01a0da',
      },
      // {
      //   name: 'type',
      //   description: '作品类型：图文笔记 normal、视频笔记 vedio、长笔记 multi',
      //   placeholder: 'normal',
      // },
    ],
    examples: ['xhsdiscover://item/6879e557000000000d01a0da', 'xhsdiscover://item/discovery.6879e557000000000d01a0da'],
  },
  {
    id: 'xiaohongshu-video-feed',
    name: '视频笔记',
    description: '打开视频笔记详情',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://video_feed/{note_id}',
    slots: [
      {
        name: 'note_id',
        description: '视频笔记 ID',
        placeholder: '685e3d13000000000b01c528',
      },
    ],
    examples: ['xhsdiscover://video_feed/685e3d13000000000b01c528'],
  },
  {
    id: 'xiaohongshu-home-explore',
    name: '首页-发现',
    description: '打开小红书首页发现 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://home/explore',
    examples: ['xhsdiscover://home/explore'],
  },
  {
    id: 'xiaohongshu-home-follow',
    name: '首页-关注',
    description: '打开小红书首页关注 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://home/follow',
    examples: ['xhsdiscover://home/follow'],
  },
  {
    id: 'xiaohongshu-home-localfeed',
    name: '首页-同城',
    description: '打开小红书首页同城 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://home/localfeed',
    examples: ['xhsdiscover://home/localfeed'],
  },
  {
    id: 'xiaohongshu-user',
    name: '用户主页',
    description: '打开用户主页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://user/{user_id}',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID。如果为 me，则打开当前用户的主页（其他 URL Scheme 同理）',
        placeholder: '6864e7a5000000001d01546a',
      },
    ],
    examples: [
      'xhsuserprofile://user_id=6864e7a5000000001d01546a',
      'xhsdiscover://user/user.6864e7a5000000001d01546a',
      'xhsdiscover://user/me',
    ],
  },
  {
    id: 'xiaohongshu-user-tab',
    name: '用户主页-Tab',
    description: '打开用户主页的指定 Tab 页面',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://user/{user_id}?tab={tab}',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID',
        placeholder: '6864e7a5000000001d01546a',
      },
      {
        name: 'tab',
        description:
          'Tab 枚举值：笔记 note（默认）、收藏 board、收藏-笔记 board.note、收藏-专辑 board.board、收藏-话题 board.tag（似乎不起作用）、@我 atMe、商品 goods（似乎不起作用）',
        placeholder: 'note',
      },
    ],
    examples: ['xhsdiscover://user/6864e7a5000000001d01546a?tab=note'],
  },
  {
    id: 'xiaohongshu-user-followers',
    name: '用户-粉丝列表',
    description: '打开用户的粉丝列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://user/{user_id}/followers',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID',
        placeholder: '6864e7a5000000001d01546a',
      },
    ],
    examples: ['xhsdiscover://user/6864e7a5000000001d01546a/followers'],
  },
  {
    id: 'xiaohongshu-draft-list',
    name: '我的草稿',
    description: '打开我的草稿',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://draft_list',
    examples: ['xhsdiscover://draft_list'],
  },
  {
    id: 'xiaohongshu-history-comment-posted',
    name: '我的评论',
    description: '打开我的评论',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://history_comment/posted',
    examples: ['xhsdiscover://history_comment/posted'],
  },
  {
    id: 'xiaohongshu-browsing-history',
    name: '浏览记录',
    description: '打开浏览记录',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://browsinghistory',
    examples: ['xhsdiscover://browsinghistory'],
  },
  {
    id: 'xiaohongshu-wallet',
    name: '我的钱包',
    description: '打开我的钱包',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://rn/wallet-rn/user/wallet',
    examples: ['xhsdiscover://rn/wallet-rn/user/wallet'],
  },
  {
    id: 'xiaohongshu-post',
    name: '发布作品',
    description: '打开发布作品（从相册选择）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://post',
    examples: ['xhsdiscover://post'],
  },
  {
    id: 'xiaohongshu-hey-home-feed',
    name: '日常',
    description: '打开日常页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://hey_home_feed',
    examples: ['xhsdiscover://hey_home_feed'],
  },
  {
    id: 'xiaohongshu-hey-post',
    name: '发布日常（Hey）',
    description: '打开日常发布',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://hey_post',
    examples: ['xhsdiscover://hey_post'],
  },
  {
    id: 'xiaohongshu-search-recommend',
    name: '搜索',
    description: '打开搜索页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://search/recommend',
    examples: ['xhsdiscover://search/recommend'],
  },
  {
    id: 'xiaohongshu-search-result',
    name: '搜索结果',
    description: '打开搜索并搜索指定关键词',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://search/result?keyword={keyword}',
    slots: [
      {
        name: 'keyword',
        description: '搜索关键词',
        placeholder: '霞浦',
      },
    ],
    examples: ['xhsdiscover://search/keyword=霞浦'],
  },
  {
    id: 'xiaohongshu-topic',
    name: '话题',
    description: '打开话题（标签）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://topic/{topic_id}',
    slots: [
      {
        name: 'topic_id',
        description: '话题 ID',
        placeholder: '5bf508d1e1921600010c101e',
      },
    ],
    examples: ['xhsdiscover://topic?topicId=5bf508d1e1921600010c101e'],
  },
  {
    id: 'xiaohongshu-board',
    name: '专辑页',
    description: '打开专辑页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://board/{board_id}',
    slots: [
      {
        name: 'board_id',
        description: '专辑 ID',
        placeholder: '632d974e000000000101d759',
      },
    ],
    examples: ['xhsdiscover://board/632d974e000000000101d759'],
  },
  {
    id: 'xiaohongshu-notification',
    name: '消息',
    description: '打开小红书消息 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://message/notification',
    examples: ['xhsdiscover://message/notification'],
  },
  {
    id: 'xiaohongshu-message-collections',
    name: '消息-赞和收藏',
    description: '打开收到的赞和收藏消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://message/collections',
    examples: ['xhsdiscover://message/collections'],
  },
  {
    id: 'xiaohongshu-message-followers',
    name: '消息-新增关注',
    description: '打开新增关注消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://message/followers',
    examples: ['xhsdiscover://message/followers'],
  },
  {
    id: 'xiaohongshu-message-comments',
    name: '消息-评论和 @',
    description: '打开评论和 @ 消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://message/comments',
    examples: ['xhsdiscover://message/comments'],
  },
  {
    id: 'xiaohongshu-message-strangers',
    name: '消息-陌生人消息',
    description: '打开陌生人消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://message/strangers',
    examples: ['xhsdiscover://message/strangers'],
  },
  {
    id: 'xiaohongshu-recommend-user',
    name: '发现好友',
    description: '打开发现好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://recommend/user',
    examples: ['xhsdiscover://recommend/user'],
  },
  {
    id: 'xiaohongshu-recommend-contacts',
    name: '通讯录好友',
    description: '打开通讯录好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://recommend/contacts',
    examples: ['xhsdiscover://recommend/contacts'],
  },
  {
    id: 'xiaohongshu-recommend-weibo',
    name: '微博好友',
    description: '打开微博好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://recommend/weibo',
    examples: ['xhsdiscover://recommend/weibo'],
  },
  {
    id: 'xiaohongshu-live-audience',
    name: '直播间',
    description: '打开直播间',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://live_audience?room_id={room_id}',
    slots: [
      {
        name: 'room_id',
        description: '直播间 ID',
        placeholder: '123456',
      },
    ],
    examples: ['xhsdiscover://live_audience?room_id=123456'],
  },
  {
    id: 'xiaohongshu-live-square',
    name: '直播广场',
    description: '打开直播广场',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://live_square',
    examples: ['xhsdiscover://live_square'],
  },
  {
    id: 'xiaohongshu-shopping-cart',
    name: '购物车',
    description: '打开购物车',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://rn/lancer-slim/user/shopping_cart',
    examples: ['xhsdiscover://rn/lancer-slim/user/shopping_cart'],
  },
  {
    id: 'xiaohongshu-home-store',
    name: '友好市集',
    description: '打开友好市集（新版商城）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://home/store',
    examples: ['xhsdiscover://home/store'],
  },
  {
    id: 'xiaohongshu-mall',
    name: '商城（旧版）',
    description: '打开旧版商城首页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://mall',
    examples: ['xhsdiscover://mall'],
    deprecated: true,
  },
  {
    id: 'xiaohongshu-goods-detail',
    name: '商品详情',
    description: '打开商品详情',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://goods_detail/{goods_id}',
    slots: [
      {
        name: 'goods_id',
        description: '商品 ID',
        placeholder: '644778b984bec4000192c772',
      },
    ],
    examples: ['xhsdiscover://goods_detail/644778b984bec4000192c772'],
  },
  {
    id: 'xiaohongshu-settings',
    name: '设置',
    description: '打开设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://settings',
    examples: ['xhsdiscover://settings'],
  },
  {
    id: 'xiaohongshu-general-setting',
    name: '设置-通用',
    description: '打开通用设置',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://general_setting',
    examples: ['xhsdiscover://general_setting'],
  },
  {
    id: 'xiaohongshu-system-settings',
    name: '系统设置',
    description: '打开小红书系统设置（iOS）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://system_settings',
    examples: ['xhsdiscover://system_settings'],
  },
  {
    id: 'xiaohongshu-account-bind',
    name: '账号与安全',
    description: '打开账号与安全',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://account/bind',
    examples: ['xhsdiscover://account/bind'],
  },
  {
    id: 'xiaohongshu-account-bind-phone',
    name: '绑定手机号',
    description: '打开绑定手机号',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://account/bind/phone',
    examples: ['xhsdiscover://account/bind/phone'],
  },
  {
    id: 'xiaohongshu-help-center',
    name: '设置-帮助与客服',
    description: '打开设置帮助与客服',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-04T00:00:00Z',
    urlSchemeTemplate: 'xhsdiscover://rn/eva-seraph/customHelpCenter/home',
    examples: ['xhsdiscover://rn/eva-seraph/customHelpCenter/home'],
  },

  // TODO: 入口在哪？不起作用？
  // {
  //   id: 'xiaohongshu-guang',
  //   name: '逛逛',
  //   description: '打开逛逛',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://guang/<note_id>',
  //   slots: [
  //     {
  //       name: 'note_id',
  //       description: '笔记 ID',
  //       placeholder: '6879e557000000000d01a0da',
  //     },
  //   ],
  //   examples: ['xhsdiscover://guang/6879e557000000000d01a0da'],
  // },
  // TODO: 举报谁？
  // {
  //   id: 'xiaohongshu-report',
  //   name: '举报功能',
  //   description: '打开举报功能页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://report?type=<type>',
  //   slots: [
  //     {
  //       name: 'type',
  //       description: '举报类型',
  //       placeholder: 'note',
  //     },
  //   ],
  //   examples: ['xhsdiscover://report?type=note'],
  // },
  // TODO: 不起作用？
  // {
  //   id: 'xiaohongshu-guang',
  //   name: '逛逛',
  //   description: '打开逛逛',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://guang/<note_id>',
  //   slots: [
  //     {
  //       name: 'note_id',
  //       description: '笔记 ID',
  //       placeholder: '688f3104000000002501683c',
  //     },
  //   ],
  //   examples: ['xhsdiscover://guang/688f3104000000002501683c'],
  // },
  // {
  //   id: 'xiaohongshu-note-comments',
  //   name: '笔记评论',
  //   description: '打开笔记评论',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://comments/<note_id>?uid=<user_id>',
  //   slots: [
  //     {
  //       name: 'note_id',
  //       description: '笔记 ID',
  //       placeholder: '6879e557000000000d01a0da',
  //     },
  //     {
  //       name: 'user_id',
  //       description: '笔记作者用户 ID',
  //       placeholder: '6864e7a5000000001d01546a',
  //     },
  //   ],
  //   examples: ['xhsdiscover://comments/6879e557000000000d01a0da?uid=6864e7a5000000001d01546a'],
  // },
  // {
  //   id: 'xiaohongshu-post-video',
  //   name: '发布视频',
  //   description: '打开发布视频页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://post_video',
  //   examples: ['xhsdiscover://post_video'],
  // },
  // {
  //   id: 'xiaohongshu-dark-mode-setting',
  //   name: '深色模式',
  //   description: '打开深色模式设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://dark_mode_setting',
  //   examples: ['xhsdiscover://dark_mode_setting'],
  // },
  // {
  //   id: 'xiaohongshu-choose-share-user',
  //   name: '选择分享用户',
  //   description: '打开选择分享用户页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://choose_share_user',
  //   examples: ['xhsdiscover://choose_share_user'],
  // },
  // {
  //   id: 'xiaohongshu-goods-detail',
  //   name: '商品详情',
  //   description: '打开商品详情',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://page/goods/<goods_id>',
  //   slots: [
  //     {
  //       name: 'goods_id',
  //       description: '商品 ID',
  //       placeholder: '644778b984bec4000192c772',
  //     },
  //   ],
  //   examples: ['xhsdiscover://page/goods/644778b984bec4000192c772'],
  // },
  // {
  //   id: 'xiaohongshu-spl',
  //   name: '商品列表',
  //   description: '打开商品列表',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://spl/<spl_id>',
  //   slots: [
  //     {
  //       name: 'spl_id',
  //       description: '商品列表 ID',
  //       placeholder: '57c555b78340c36ad3875529',
  //     },
  //   ],
  //   examples: ['xhsdiscover://spl/57c555b78340c36ad3875529'],
  // },
  // {
  //   id: 'xiaohongshu-spv',
  //   name: '商品展示',
  //   description: '打开商品展示页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-04T00:00:00Z',
  //   urlSchemeTemplate: 'xhsdiscover://spv/<spv_id>',
  //   slots: [
  //     {
  //       name: 'spv_id',
  //       description: '商品展示 ID',
  //       placeholder: '57c555b78340c36ad3875529',
  //     },
  //   ],
  //   examples: ['xhsdiscover://spv/57c555b78340c36ad3875529'],
  // },
] as const

export default XIAOHONGSHU
