import type { UrlSchemeWithoutCategory } from '@/types'

const XIAOHONGSHU: UrlSchemeWithoutCategory[] = [
  {
    id: 'xiaohongshu-item-detail',
    name: '图文笔记',
    description: '打开图文笔记详情',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://item/<note_id>',
    slots: [
      {
        name: 'note_id',
        description: '图文笔记 ID',
        placeholder: '6879e557000000000d01a0da',
      },
      // {
      //   name: 'type',
      //   description: '作品类型：图文笔记 normal、视频笔记 vedio、长笔记 multi',
      //   placeholder: 'normal',
      // },
    ],
    examples: ['xhsdiscover://item/6879e557000000000d01a0da', 'xhsdiscover://item/discovery.6879e557000000000d01a0da'],
  },
  {
    id: 'xiaohongshu-video-feed',
    name: '视频笔记',
    description: '打开视频笔记详情',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://video_feed/<note_id>',
    slots: [
      {
        name: 'note_id',
        description: '视频笔记 ID',
        placeholder: '685e3d13000000000b01c528',
      },
    ],
    examples: ['xhsdiscover://video_feed/685e3d13000000000b01c528'],
  },
  {
    id: 'xiaohongshu-home-explore',
    name: '首页-发现',
    description: '打开小红书首页发现 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://home/explore',
    examples: ['xhsdiscover://home/explore'],
  },
  {
    id: 'xiaohongshu-home-follow',
    name: '首页-关注',
    description: '打开小红书首页关注 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://home/follow',
    examples: ['xhsdiscover://home/follow'],
  },
  {
    id: 'xiaohongshu-home-localfeed',
    name: '首页-同城',
    description: '打开小红书首页同城 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://home/localfeed',
    examples: ['xhsdiscover://home/localfeed'],
  },
  {
    id: 'xiaohongshu-user',
    name: '用户主页',
    description: '打开用户主页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://user/<user_id>',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID。如果为 me，则打开当前用户的主页（其他 URL Scheme 同理）',
        placeholder: '6864e7a5000000001d01546a',
      },
    ],
    examples: [
      'xhsuserprofile://user_id=6864e7a5000000001d01546a',
      'xhsdiscover://user/user.6864e7a5000000001d01546a',
      'xhsdiscover://user/me',
    ],
  },
  {
    id: 'xiaohongshu-user-tab',
    name: '用户主页-Tab',
    description: '打开用户主页的指定 Tab 页面。',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://user/<user_id>?tab=<tab>',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID',
        placeholder: '6864e7a5000000001d01546a',
      },
      {
        name: 'tab',
        description:
          'Tab 枚举值：笔记 note（默认）、收藏 board、收藏-笔记 board.note、收藏-专辑 board.board、收藏-话题 board.tag（似乎不起作用）、@我 atMe、商品 goods（似乎不起作用）',
        placeholder: 'note',
      },
    ],
    examples: ['xhsdiscover://user/6864e7a5000000001d01546a?tab=note'],
  },
  {
    id: 'xiaohongshu-user-followers',
    name: '用户-粉丝列表',
    description: '打开用户的粉丝列表',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://user/<user_id>/followers',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID',
        placeholder: '6864e7a5000000001d01546a',
      },
    ],
    examples: ['xhsdiscover://user/6864e7a5000000001d01546a/followers'],
  },
  {
    id: 'xiaohongshu-hey-home-feed',
    name: '记录我的日常',
    description: '打开记录我的日常',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://hey_home_feed',
    examples: ['xhsdiscover://hey_home_feed'],
  },
  // TODO: 这是？
  // {
  //   id: 'xiaohongshu-guang',
  //   name: '精选视频页',
  //   description: '打开精选视频页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://guang/<note_id>',
  //   slots: [
  //     {
  //       name: 'note_id',
  //       description: '笔记 ID',
  //       placeholder: '688f3104000000002501683c',
  //     },
  //   ],
  //   examples: ['xhsdiscover://guang/688f3104000000002501683c'],
  // },
  // TODO: 失效？
  // {
  //   id: 'xiaohongshu-note-comments',
  //   name: '笔记评论',
  //   description: '打开笔记评论',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://comments/<note_id>?uid=<user_id>',
  //   slots: [
  //     {
  //       name: 'note_id',
  //       description: '笔记 ID',
  //       placeholder: '6879e557000000000d01a0da',
  //     },
  //     {
  //       name: 'user_id',
  //       description: '笔记作者用户 ID',
  //       placeholder: '6864e7a5000000001d01546a',
  //     },
  //   ],
  //   examples: ['xhsdiscover://comments/6879e557000000000d01a0da?uid=6864e7a5000000001d01546a'],
  // },
  {
    id: 'xiaohongshu-notification',
    name: '消息',
    description: '打开小红书消息 Tab',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://message/notification',
    examples: ['xhsdiscover://message/notification'],
  },
  {
    id: 'xiaohongshu-message-collections',
    name: '消息-赞和收藏',
    description: '打开收到的赞和收藏消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://message/collections',
    examples: ['xhsdiscover://message/collections'],
  },
  {
    id: 'xiaohongshu-message-followers',
    name: '消息-新增关注',
    description: '打开新增关注消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://message/followers',
    examples: ['xhsdiscover://message/followers'],
  },
  {
    id: 'xiaohongshu-message-comments',
    name: '消息-评论和 @',
    description: '打开评论和 @ 消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://message/comments',
    examples: ['xhsdiscover://message/comments'],
  },
  {
    id: 'xiaohongshu-message-strangers',
    name: '消息-陌生人消息',
    description: '打开陌生人消息',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://message/strangers',
    examples: ['xhsdiscover://message/strangers'],
  },
  {
    id: 'xiaohongshu-recommend-user',
    name: '发现好友',
    description: '打开发现好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://recommend/user',
    examples: ['xhsdiscover://recommend/user'],
  },
  {
    id: 'xiaohongshu-recommend-contacts',
    name: '通讯录好友',
    description: '打开通讯录好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://recommend/contacts',
    examples: ['xhsdiscover://recommend/contacts'],
  },
  {
    id: 'xiaohongshu-recommend-weibo',
    name: '微博好友',
    description: '打开微博好友',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://recommend/weibo',
    examples: ['xhsdiscover://recommend/weibo'],
  },
  {
    id: 'xiaohongshu-search-recommend',
    name: '搜索',
    description: '打开搜索页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://search/recommend',
    examples: ['xhsdiscover://search/recommend'],
  },
  {
    id: 'xiaohongshu-search-result',
    name: '搜索结果',
    description: '打开搜索并搜索指定关键词',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://search/result?keyword=<keyword>',
    slots: [
      {
        name: 'keyword',
        description: '搜索关键词',
        placeholder: '霞浦',
      },
    ],
    examples: ['xhsdiscover://search/keyword=霞浦'],
  },

  {
    id: 'xiaohongshu-home-store',
    name: '友好市集（新版）',
    description: '打开友好市集（新版商城）',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://home/store',
    examples: ['xhsdiscover://home/store'],
  },
  {
    id: 'xiaohongshu-mall',
    name: '商城（旧版）',
    description: '打开旧版商城首页',
    contributors: ['toFrankie'],
    updatedAt: '2025-08-03T00:00:00Z',
    urlTemplate: 'xhsdiscover://mall',
    examples: ['xhsdiscover://mall'],
    deprecated: true,
  },
  // TODO: 不起作用？
  // {
  //   id: 'xiaohongshu-goods-detail',
  //   name: '商品详情页',
  //   description: '打开商品详情页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://page/goods/<goods_id>',
  //   slots: [
  //     {
  //       name: 'goods_id',
  //       description: '商品 ID',
  //       placeholder: '644778b984bec4000192c772',
  //     },
  //   ],
  //   examples: ['xhsdiscover://page/goods/644778b984bec4000192c772'],
  // },

  // TODO: 以下待验证
  // {
  //   id: 'xiaohongshu-spl',
  //   name: '商品列表页',
  //   description: '打开商品列表页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://spl/<spl_id>',
  //   slots: [
  //     {
  //       name: 'spl_id',
  //       description: '商品列表 ID',
  //       placeholder: '57c555b78340c36ad3875529',
  //     },
  //   ],
  //   examples: ['xhsdiscover://spl/57c555b78340c36ad3875529'],
  // },
  // {
  //   id: 'xiaohongshu-spv',
  //   name: '商品展示页',
  //   description: '打开商品展示页（v4.16+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://spv/<spv_id>',
  //   slots: [
  //     {
  //       name: 'spv_id',
  //       description: '商品展示 ID',
  //       placeholder: '57c555b78340c36ad3875529',
  //     },
  //   ],
  //   examples: ['xhsdiscover://spv/57c555b78340c36ad3875529'],
  // },
  // {
  //   id: 'xiaohongshu-post',
  //   name: '发布作品（相册）',
  //   description: '打开发布作品页面（相册，v5.22+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://post?hash_tags=<hash_tags>',
  //   slots: [
  //     {
  //       name: 'hash_tags',
  //       description: '话题标签（JSON格式）',
  //       placeholder: '[{"id":"52d0deb1b4c4d655316b7d21"}]',
  //     },
  //   ],
  //   examples: ['xhsdiscover://post?hash_tags=[{"id":"52d0deb1b4c4d655316b7d21"}]'],
  // },
  // {
  //   id: 'xiaohongshu-post-note',
  //   name: '发布笔记（忽略草稿）',
  //   description: '打开发布笔记页面（忽略草稿，v5.22+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://post_note?ignore_draft=<ignore_draft>',
  //   slots: [
  //     {
  //       name: 'ignore_draft',
  //       description: '是否忽略草稿',
  //       placeholder: 'true',
  //     },
  //   ],
  //   examples: ['xhsdiscover://post_note?ignore_draft=true'],
  // },
  // {
  //   id: 'xiaohongshu-post-video',
  //   name: '发布视频',
  //   description: '打开发布视频页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://post_video',
  //   examples: ['xhsdiscover://post_video'],
  // },
  // {
  //   id: 'xiaohongshu-notes-draft-box',
  //   name: '草稿箱',
  //   description: '打开草稿箱',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://notes_draft_box',
  //   examples: ['xhsdiscover://notes_draft_box'],
  // },
  // {
  //   id: 'xiaohongshu-topic',
  //   name: '话题/标签页',
  //   description: '打开话题/标签页（iOS）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://topic?topicId=<topic_id>',
  //   slots: [
  //     {
  //       name: 'topic_id',
  //       description: '话题ID',
  //       placeholder: '5e9c9d5f0000000001008e19',
  //     },
  //   ],
  //   examples: ['xhsdiscover://topic?topicId=5e9c9d5f0000000001008e19'],
  // },
  // {
  //   id: 'xiaohongshu-page-topics',
  //   name: '新话题页',
  //   description: '打开新话题页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://page/topics/<topic_id>',
  //   slots: [
  //     {
  //       name: 'topic_id',
  //       description: '话题ID',
  //       placeholder: '5e9c9d5f0000000001008e19',
  //     },
  //   ],
  //   examples: ['xhsdiscover://page/topics/5e9c9d5f0000000001008e19'],
  // },
  // {
  //   id: 'xiaohongshu-system-settings',
  //   name: '系统设置',
  //   description: '打开系统设置（v5.8+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://system_settings',
  //   examples: ['xhsdiscover://system_settings'],
  // },
  // {
  //   id: 'xiaohongshu-account-bind',
  //   name: '账号绑定',
  //   description: '打开账号绑定页面（v5.0+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://account/bind',
  //   examples: ['xhsdiscover://account/bind'],
  // },
  // {
  //   id: 'xiaohongshu-account-bind-phone',
  //   name: '手机号绑定',
  //   description: '打开手机号绑定页面（v5.0+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://account/bind/phone?bind_phone=<phone>',
  //   slots: [
  //     {
  //       name: 'phone',
  //       description: '手机号',
  //       placeholder: '138****1234',
  //     },
  //   ],
  //   examples: ['xhsdiscover://account/bind/phone?bind_phone=138****1234'],
  // },
  // {
  //   id: 'xiaohongshu-dark-mode-setting',
  //   name: '深色模式设置',
  //   description: '打开深色模式设置',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://dark_mode_setting',
  //   examples: ['xhsdiscover://dark_mode_setting'],
  // },
  // {
  //   id: 'xiaohongshu-choose-share-user',
  //   name: '选择分享用户',
  //   description: '打开选择分享用户页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://choose_share_user',
  //   examples: ['xhsdiscover://choose_share_user'],
  // },
  // {
  //   id: 'xiaohongshu-report',
  //   name: '举报功能',
  //   description: '打开举报功能页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://report?type=<type>',
  //   slots: [
  //     {
  //       name: 'type',
  //       description: '举报类型',
  //       placeholder: 'note',
  //     },
  //   ],
  //   examples: ['xhsdiscover://report?type=note'],
  // },
  // {
  //   id: 'xiaohongshu-list',
  //   name: '标签页',
  //   description: '打开标签页（v4.8+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://list/<tag_id>',
  //   slots: [
  //     {
  //       name: 'tag_id',
  //       description: '标签ID',
  //       placeholder: '52d0deb1b4c4d655316b7d21',
  //     },
  //   ],
  //   examples: ['xhsdiscover://list/52d0deb1b4c4d655316b7d21'],
  // },
  // {
  //   id: 'xiaohongshu-board',
  //   name: '专辑页',
  //   description: '打开专辑页（v3.2+）',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://board/<board_id>',
  //   slots: [
  //     {
  //       name: 'board_id',
  //       description: '专辑ID',
  //       placeholder: '52d0deb1b4c4d655316b7d21',
  //     },
  //   ],
  //   examples: ['xhsdiscover://board/52d0deb1b4c4d655316b7d21'],
  // },
  // {
  //   id: 'xiaohongshu-live-audience',
  //   name: '直播播放页',
  //   description: '打开直播播放页',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://live_audience?room_id=<room_id>',
  //   slots: [
  //     {
  //       name: 'room_id',
  //       description: '直播间ID',
  //       placeholder: '123456',
  //     },
  //   ],
  //   examples: ['xhsdiscover://live_audience?room_id=123456'],
  // },
  // {
  //   id: 'xiaohongshu-hey-goal',
  //   name: '打卡目标设置',
  //   description: '打开打卡目标设置页面',
  //   contributors: ['toFrankie'],
  //   updatedAt: '2025-08-03T00:00:00Z',
  //   urlTemplate: 'xhsdiscover://hey_goal?clockin_count=<count>',
  //   slots: [
  //     {
  //       name: 'count',
  //       description: '打卡次数',
  //       placeholder: '5',
  //     },
  //   ],
  //   examples: ['xhsdiscover://hey_goal?clockin_count=5'],
  // },
] as const

export default XIAOHONGSHU
