import type { UrlSchemeWithoutCategory } from '@/types'

const ZHIHU: UrlSchemeWithoutCategory[] = [
  {
    id: 'zhihu-feed-item-recommend',
    name: '首页推荐流',
    description: '打开知乎首页推荐流',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://feed/item/recommend',
    examples: ['zhihu://feed/item/recommend'],
  },
  {
    id: 'zhihu-people',
    name: '用户主页',
    description: '打开知乎用户主页',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://people/{user_id}',
    slots: [
      {
        name: 'user_id',
        description: '用户 ID',
        placeholder: 'tofrankie',
      },
    ],
    examples: ['zhihu://people/tofrankie'],
  },
  {
    id: 'zhihu-article',
    name: '文章',
    description: '打开知乎文章',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://articles/{article_id}',
    slots: [
      {
        name: 'article_id',
        description: '文章 ID',
        placeholder: '687430865',
      },
    ],
    examples: ['zhihu://articles/687430865'],
  },
  {
    id: 'zhihu-question',
    name: '问题',
    description: '打开知乎问题',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://questions/{question_id}',
    slots: [
      {
        name: 'question_id',
        description: '问题 ID',
        placeholder: '608906016',
      },
    ],
    examples: ['zhihu://questions/608906016'],
  },
  {
    id: 'zhihu-answer',
    name: '回答',
    description: '打开知乎回答',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://answers/{answer_id}',
    slots: [
      {
        name: 'answer_id',
        description: '回答 ID',
        placeholder: '1916817252302422464',
      },
    ],
    examples: ['zhihu://answers/1916817252302422464'],
  },
  {
    id: 'zhihu-answer-editor',
    name: '写回答',
    description: '打开知乎写回答',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://answer/editor/{question_id}',
    slots: [
      {
        name: 'question_id',
        description: '问题 ID',
        placeholder: '608906016',
      },
    ],
    examples: ['zhihu://answer/editor/608906016'],
  },
  {
    id: 'zhihu-column',
    name: '专栏',
    description: '打开知乎专栏',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://columns/{column_id}',
    slots: [
      {
        name: 'column_id',
        description: '专栏 ID',
        placeholder: 'c_1369940836248158208',
      },
    ],
    examples: ['zhihu://columns/c_1369940836248158208'],
  },
  {
    id: 'zhihu-collection',
    name: '收藏夹',
    description: '打开知乎收藏夹',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://collection/{collection_id}',
    slots: [
      {
        name: 'collection_id',
        description: '收藏夹 ID',
        placeholder: '375006326',
      },
    ],
    examples: ['zhihu://collection/375006326'],
  },
  {
    id: 'zhihu-zvideo',
    name: '视频',
    description: '打开知乎视频',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://zvideo/{video_id}',
    slots: [
      {
        name: 'video_id',
        description: '视频 ID',
        placeholder: '1326680693162602496',
      },
    ],
    examples: ['zhihu://zvideo/1326680693162602496'],
  },
  {
    id: 'zhihu-ask',
    name: '提问',
    description: '打开知乎新建提问',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://ask',
    examples: ['zhihu://ask'],
  },
  {
    id: 'zhihu-pin',
    name: '想法',
    description: '打开知乎想法',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://pin/{pin_id}',
    slots: [
      {
        name: 'pin_id',
        description: '想法 ID',
        placeholder: '1092897180339212288',
      },
    ],
    examples: ['zhihu://pin/1092897180339212288'],
  },
  {
    id: 'zhihu-topic',
    name: '话题',
    description: '打开知乎话题',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://topics/{topic_id}',
    slots: [
      {
        name: 'topic_id',
        description: '话题 ID',
        placeholder: '19677261',
      },
    ],
    examples: ['zhihu://topics/19677261'],
  },
  {
    id: 'zhihu-search',
    name: '搜索',
    description: '打开知乎搜索',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://search',
    examples: ['zhihu://search'],
  },
  {
    id: 'zhihu-search-result',
    name: '搜索内容',
    description: '打开知乎搜索并搜索指定内容',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://search?q={keyword}',
    slots: [
      {
        name: 'keyword',
        description: '搜索关键词',
        placeholder: '刘看山',
      },
    ],
    examples: ['zhihu://search?q=刘看山'],
  },
  {
    id: 'zhihu-vip-purchase',
    name: '盐选会员',
    description: '打开知乎盐选会员',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://vip/purchase',
    examples: ['zhihu://vip/purchase'],
  },
  {
    id: 'zhihu-settings',
    name: '设置',
    description: '打开知乎设置',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://settings',
    examples: ['zhihu://settings'],
  },
  {
    id: 'zhihu-dynamic-settings',
    name: '动态设置',
    description: '打开知乎动态设置',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://dynamic/settings',
    examples: ['zhihu://dynamic/settings'],
  },
  {
    id: 'zhihu-codereader',
    name: '扫一扫',
    description: '打开知乎二维码扫描',
    contributors: ['tofrankie'],
    updatedAt: '2025-08-05T00:00:00Z',
    urlSchemeTemplate: 'zhihu://codereader',
    examples: ['zhihu://codereader'],
  },
  // TODO: 不起作用，暂时注释
  // {
  //   id: 'zhihu-notifications',
  //   name: '通知',
  //   description: '打开知乎通知',
  //   contributors: ['tofrankie'],
  //   updatedAt: '2025-08-05T00:00:00Z',
  //   urlSchemeTemplate: 'zhihu://notifications',
  //   examples: ['zhihu://notifications'],
  //   deprecated: true,
  // },
]

export default ZHIHU
