import type { URLScheme, Category } from '@/types'

export const GITHUB_REPO_URL =
  'https://github.com/toFrankie/url-scheme-collection'

export const GITHUB_ISSUES_URL = `${GITHUB_REPO_URL}/issues`

export const GITHUB_PULLS_URL = `${GITHUB_REPO_URL}/pulls`

// 基础分类定义（不包含 count 和 icon）
const BASE_CATEGORIES = [
  {
    id: 'app-store',
    name: '应用商店',
    description: 'iOS App Store 和 Android 应用商店相关',
  },
  {
    id: 'social',
    name: '社交应用',
    description: '微信、QQ、微博等社交应用',
  },
  {
    id: 'payment',
    name: '支付应用',
    description: '支付宝、微信支付等支付应用',
  },
  {
    id: 'navigation',
    name: '导航应用',
    description: '高德地图、百度地图等导航应用',
  },
  {
    id: 'music',
    name: '音乐应用',
    description: '网易云音乐、QQ音乐等音乐应用',
  },
  {
    id: 'video',
    name: '视频应用',
    description: '抖音、快手、B站等视频应用',
  },
  {
    id: 'shopping',
    name: '购物应用',
    description: '淘宝、京东、拼多多等购物应用',
  },
  {
    id: 'tools',
    name: '工具应用',
    description: '计算器、时钟、天气等工具应用',
  },
  {
    id: 'education',
    name: '教育应用',
    description: '学习、考试、培训等教育相关应用',
  },
  {
    id: 'health',
    name: '健康应用',
    description: '运动、医疗、健康管理等应用',
  },
  {
    id: 'finance',
    name: '金融应用',
    description: '银行、证券、理财等金融应用',
  },
  {
    id: 'travel',
    name: '旅行应用',
    description: '酒店、机票、旅游等旅行应用',
  },
  {
    id: 'food',
    name: '美食应用',
    description: '外卖、团购、美食推荐等应用',
  },
  {
    id: 'entertainment',
    name: '娱乐应用',
    description: '游戏、直播、娱乐等应用',
  },
  {
    id: 'productivity',
    name: '效率应用',
    description: '办公、笔记、项目管理等应用',
  },
]

// 计算每个分类的 URL Scheme 数量
const calculateCategoryCounts = (schemes: URLScheme[]) => {
  const counts: Record<string, number> = {}

  schemes.forEach(scheme => {
    if (!scheme.deprecated) {
      // 不计算已废弃的
      counts[scheme.category] = (counts[scheme.category] || 0) + 1
    }
  })

  return counts
}

export const SAMPLE_URL_SCHEMES: URLScheme[] = [
  {
    id: 'app-store-ios',
    name: 'iOS App Store 应用详情',
    category: 'app-store',
    urlTemplate: 'itms-apps://itunes.apple.com/cn/app/<bundle_id>/id<apple_id>',
    slots: [
      {
        name: 'bundle_id',
        description: '应用的 Bundle ID',
        placeholder: '例如：wechat',
        required: true,
      },
      {
        name: 'apple_id',
        description: 'Apple 分配的应用 ID',
        placeholder: '例如：414478124',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 iOS App Store 中指定应用的详情页面',
    examples: [
      'itms-apps://itunes.apple.com/cn/app/wechat/id414478124',
      'itms-apps://itunes.apple.com/cn/app/qq/id444934666',
    ],
  },
  {
    id: 'app-store-android',
    name: 'Android 应用商店详情',
    category: 'app-store',
    urlTemplate: 'market://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: 'Android 应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 Android 应用商店中指定应用的详情页面',
    examples: [
      'market://details?id=com.tencent.mm',
      'market://details?id=com.tencent.mobileqq',
    ],
  },
  {
    id: 'app-store-search',
    name: 'iOS App Store 搜索',
    category: 'app-store',
    urlTemplate:
      'itms-apps://search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?media=software&term=<search_term>',
    slots: [
      {
        name: 'search_term',
        description: '搜索关键词',
        placeholder: '例如：微信',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '在 iOS App Store 中搜索应用',
    examples: [
      'itms-apps://search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?media=software&term=微信',
    ],
  },
  {
    id: 'app-store-category',
    name: 'iOS App Store 分类',
    category: 'app-store',
    urlTemplate: 'itms-apps://itunes.apple.com/cn/genre/<category_id>',
    slots: [
      {
        name: 'category_id',
        description: '分类 ID',
        placeholder: '例如：6000 (游戏)',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 iOS App Store 指定分类页面',
    examples: ['itms-apps://itunes.apple.com/cn/genre/6000'],
  },
  {
    id: 'google-play',
    name: 'Google Play 商店',
    category: 'app-store',
    urlTemplate: 'https://play.google.com/store/apps/details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: 'Android 应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 Google Play 商店中的应用详情页面',
    examples: ['https://play.google.com/store/apps/details?id=com.tencent.mm'],
  },
  {
    id: 'huawei-appgallery',
    name: '华为应用市场',
    category: 'app-store',
    urlTemplate: 'appmarket://details?pkgname=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开华为应用市场中的应用详情页面',
    examples: ['appmarket://details?pkgname=com.tencent.mm'],
  },
  {
    id: 'xiaomi-appstore',
    name: '小米应用商店',
    category: 'app-store',
    urlTemplate: 'mimarket://details?id=<package_name>',
    slots: [
      {
        name: 'package_name',
        description: '应用的包名',
        placeholder: '例如：com.tencent.mm',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开小米应用商店中的应用详情页面',
    examples: ['mimarket://details?id=com.tencent.mm'],
  },
  {
    id: 'wechat',
    name: '微信',
    category: 'social',
    urlTemplate: 'weixin://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微信应用',
    examples: ['weixin://'],
  },
  {
    id: 'wechat-scan',
    name: '微信扫一扫',
    category: 'social',
    urlTemplate: 'weixin://dl/scan',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微信扫一扫功能',
    examples: ['weixin://dl/scan'],
  },
  {
    id: 'wechat-pay-scan',
    name: '微信支付扫一扫',
    category: 'social',
    urlTemplate: 'weixin://dl/businessPay/',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微信支付扫一扫功能',
    examples: ['weixin://dl/businessPay/'],
  },
  {
    id: 'wechat-moments',
    name: '微信朋友圈',
    category: 'social',
    urlTemplate: 'weixin://dl/moments',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微信朋友圈',
    examples: ['weixin://dl/moments'],
  },
  {
    id: 'wechat-mini-program',
    name: '微信小程序',
    category: 'social',
    urlTemplate: 'weixin://dl/business/?t=*&appid=<app_id>',
    slots: [
      {
        name: 'app_id',
        description: '小程序 App ID',
        placeholder: '例如：wx1234567890',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开指定微信小程序',
    examples: ['weixin://dl/business/?t=*&appid=wx1234567890'],
  },
  {
    id: 'wechat-pay',
    name: '微信支付',
    category: 'payment',
    urlTemplate: 'weixin://app/<app_id>/',
    slots: [
      {
        name: 'app_id',
        description: '微信小程序的 App ID',
        placeholder: '例如：wx1234567890',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微信小程序或微信支付',
    examples: ['weixin://app/wx1234567890/'],
  },
  {
    id: 'alipay',
    name: '支付宝',
    category: 'payment',
    urlTemplate: 'alipay://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开支付宝应用',
    examples: ['alipay://'],
  },
  {
    id: 'deprecated-example',
    name: '已废弃的示例',
    category: 'app-store',
    urlTemplate: 'old-scheme://example',
    deprecated: true,
    lastUpdated: '2023-12-01',
    updatedBy: 'frankie',
    description: '这是一个已废弃的 URL Scheme 示例',
    examples: ['old-scheme://example'],
  },
  // 社交应用
  {
    id: 'qq',
    name: 'QQ',
    category: 'social',
    urlTemplate: 'mqq://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 QQ 应用',
    examples: ['mqq://'],
  },
  {
    id: 'weibo',
    name: '微博',
    category: 'social',
    urlTemplate: 'weibo://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开微博应用',
    examples: ['weibo://'],
  },
  {
    id: 'douyin',
    name: '抖音',
    category: 'social',
    urlTemplate: 'snssdk1128://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开抖音应用',
    examples: ['snssdk1128://'],
  },
  {
    id: 'xiaohongshu',
    name: '小红书',
    category: 'social',
    urlTemplate: 'xhsdiscover://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开小红书应用',
    examples: ['xhsdiscover://'],
  },
  {
    id: 'zhihu',
    name: '知乎',
    category: 'social',
    urlTemplate: 'zhihu://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开知乎应用',
    examples: ['zhihu://'],
  },
  // 支付应用
  {
    id: 'unionpay',
    name: '银联云闪付',
    category: 'payment',
    urlTemplate: 'uppaywallet://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开银联云闪付应用',
    examples: ['uppaywallet://'],
  },
  {
    id: 'jd-pay',
    name: '京东支付',
    category: 'payment',
    urlTemplate: 'jdpay://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开京东支付应用',
    examples: ['jdpay://'],
  },
  // 导航应用
  {
    id: 'amap',
    name: '高德地图',
    category: 'navigation',
    urlTemplate: 'iosamap://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开高德地图应用',
    examples: ['iosamap://'],
  },
  {
    id: 'baidu-map',
    name: '百度地图',
    category: 'navigation',
    urlTemplate: 'baidumap://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开百度地图应用',
    examples: ['baidumap://'],
  },
  {
    id: 'tencent-map',
    name: '腾讯地图',
    category: 'navigation',
    urlTemplate: 'qqmap://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开腾讯地图应用',
    examples: ['qqmap://'],
  },
  // 音乐应用
  {
    id: 'netease-music',
    name: '网易云音乐',
    category: 'music',
    urlTemplate: 'orpheuswidget://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开网易云音乐应用',
    examples: ['orpheuswidget://'],
  },
  {
    id: 'qq-music',
    name: 'QQ音乐',
    category: 'music',
    urlTemplate: 'qqmusic://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开 QQ音乐应用',
    examples: ['qqmusic://'],
  },
  {
    id: 'kugou',
    name: '酷狗音乐',
    category: 'music',
    urlTemplate: 'kugou://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开酷狗音乐应用',
    examples: ['kugou://'],
  },
  {
    id: 'kuwo',
    name: '酷我音乐',
    category: 'music',
    urlTemplate: 'kuwo://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开酷我音乐应用',
    examples: ['kuwo://'],
  },
  // 视频应用
  {
    id: 'bilibili',
    name: 'B站',
    category: 'video',
    urlTemplate: 'bilibili://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开B站应用',
    examples: ['bilibili://'],
  },
  {
    id: 'kuaishou',
    name: '快手',
    category: 'video',
    urlTemplate: 'gifshow://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开快手应用',
    examples: ['gifshow://'],
  },
  {
    id: 'iqiyi',
    name: '爱奇艺',
    category: 'video',
    urlTemplate: 'iqiyi://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开爱奇艺应用',
    examples: ['iqiyi://'],
  },
  {
    id: 'youku',
    name: '优酷',
    category: 'video',
    urlTemplate: 'youku://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开优酷应用',
    examples: ['youku://'],
  },
  {
    id: 'tencent-video',
    name: '腾讯视频',
    category: 'video',
    urlTemplate: 'tenvideo://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开腾讯视频应用',
    examples: ['tenvideo://'],
  },
  // 购物应用
  {
    id: 'taobao',
    name: '淘宝',
    category: 'shopping',
    urlTemplate: 'taobao://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开淘宝应用',
    examples: ['taobao://'],
  },
  {
    id: 'jd',
    name: '京东',
    category: 'shopping',
    urlTemplate: 'openapp.jdmobile://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开京东应用',
    examples: ['openapp.jdmobile://'],
  },
  {
    id: 'pinduoduo',
    name: '拼多多',
    category: 'shopping',
    urlTemplate: 'pinduoduo://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开拼多多应用',
    examples: ['pinduoduo://'],
  },
  {
    id: 'tmall',
    name: '天猫',
    category: 'shopping',
    urlTemplate: 'tmall://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开天猫应用',
    examples: ['tmall://'],
  },
  // 工具应用
  {
    id: 'calculator',
    name: '计算器',
    category: 'tools',
    urlTemplate: 'calculator://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统计算器应用',
    examples: ['calculator://'],
  },
  {
    id: 'clock',
    name: '时钟',
    category: 'tools',
    urlTemplate: 'clock://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统时钟应用',
    examples: ['clock://'],
  },
  {
    id: 'weather',
    name: '天气',
    category: 'tools',
    urlTemplate: 'weather://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统天气应用',
    examples: ['weather://'],
  },
  {
    id: 'calendar',
    name: '日历',
    category: 'tools',
    urlTemplate: 'calshow://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统日历应用',
    examples: ['calshow://'],
  },
  {
    id: 'notes',
    name: '备忘录',
    category: 'tools',
    urlTemplate: 'mobilenotes://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统备忘录应用',
    examples: ['mobilenotes://'],
  },
  {
    id: 'camera',
    name: '相机',
    category: 'tools',
    urlTemplate: 'camera://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统相机应用',
    examples: ['camera://'],
  },
  // 教育应用
  {
    id: 'zhihu-study',
    name: '知乎学习',
    category: 'education',
    urlTemplate: 'zhihu://study',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开知乎学习功能',
    examples: ['zhihu://study'],
  },
  {
    id: 'bilibili-study',
    name: 'B站学习',
    category: 'education',
    urlTemplate: 'bilibili://study/<course_id>',
    slots: [
      {
        name: 'course_id',
        description: '课程ID',
        placeholder: '例如：BV1xx411c7mu',
        required: true,
      },
    ],
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开B站指定课程',
    examples: ['bilibili://study/BV1xx411c7mu'],
  },
  {
    id: 'ximalaya',
    name: '喜马拉雅',
    category: 'education',
    urlTemplate: 'ximalaya://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开喜马拉雅应用',
    examples: ['ximalaya://'],
  },
  {
    id: 'duolingo',
    name: '多邻国',
    category: 'education',
    urlTemplate: 'duolingo://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开多邻国语言学习应用',
    examples: ['duolingo://'],
  },
  {
    id: 'coursera',
    name: 'Coursera',
    category: 'education',
    urlTemplate: 'coursera://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Coursera在线课程平台',
    examples: ['coursera://'],
  },
  {
    id: 'udemy',
    name: 'Udemy',
    category: 'education',
    urlTemplate: 'udemy://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Udemy在线学习平台',
    examples: ['udemy://'],
  },
  {
    id: 'khan-academy',
    name: '可汗学院',
    category: 'education',
    urlTemplate: 'khanacademy://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开可汗学院学习应用',
    examples: ['khanacademy://'],
  },
  // 健康应用
  {
    id: 'keep',
    name: 'Keep',
    category: 'health',
    urlTemplate: 'keep://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Keep健身应用',
    examples: ['keep://'],
  },
  {
    id: 'nike-run',
    name: 'Nike Run Club',
    category: 'health',
    urlTemplate: 'nikeplus://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Nike跑步应用',
    examples: ['nikeplus://'],
  },
  {
    id: 'strava',
    name: 'Strava',
    category: 'health',
    urlTemplate: 'strava://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Strava运动追踪应用',
    examples: ['strava://'],
  },
  {
    id: 'myfitnesspal',
    name: 'MyFitnessPal',
    category: 'health',
    urlTemplate: 'myfitnesspal://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开MyFitnessPal健康管理应用',
    examples: ['myfitnesspal://'],
  },
  {
    id: 'fitbit',
    name: 'Fitbit',
    category: 'health',
    urlTemplate: 'fitbit://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Fitbit健康追踪应用',
    examples: ['fitbit://'],
  },
  {
    id: 'apple-health',
    name: '健康',
    category: 'health',
    urlTemplate: 'x-apple-health://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开苹果健康应用',
    examples: ['x-apple-health://'],
  },
  // 金融应用
  {
    id: 'icbc',
    name: '工商银行',
    category: 'finance',
    urlTemplate: 'icbc://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开工商银行应用',
    examples: ['icbc://'],
  },
  {
    id: 'ccb',
    name: '建设银行',
    category: 'finance',
    urlTemplate: 'ccb://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开建设银行应用',
    examples: ['ccb://'],
  },
  {
    id: 'abc',
    name: '农业银行',
    category: 'finance',
    urlTemplate: 'abc://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开农业银行应用',
    examples: ['abc://'],
  },
  {
    id: 'boc',
    name: '中国银行',
    category: 'finance',
    urlTemplate: 'boc://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开中国银行应用',
    examples: ['boc://'],
  },
  {
    id: 'ant-fortune',
    name: '蚂蚁财富',
    category: 'finance',
    urlTemplate: 'antfortune://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开蚂蚁财富理财应用',
    examples: ['antfortune://'],
  },
  {
    id: 'eastmoney',
    name: '东方财富',
    category: 'finance',
    urlTemplate: 'eastmoney://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开东方财富证券应用',
    examples: ['eastmoney://'],
  },
  {
    id: 'snowball',
    name: '雪球',
    category: 'finance',
    urlTemplate: 'snowball://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开雪球投资应用',
    examples: ['snowball://'],
  },
  {
    id: 'tiger',
    name: '老虎证券',
    category: 'finance',
    urlTemplate: 'tiger://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开老虎证券应用',
    examples: ['tiger://'],
  },
  // 旅行应用
  {
    id: 'ctrip',
    name: '携程',
    category: 'travel',
    urlTemplate: 'ctrip://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开携程旅行应用',
    examples: ['ctrip://'],
  },
  {
    id: 'fliggy',
    name: '飞猪',
    category: 'travel',
    urlTemplate: 'fliggy://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开飞猪旅行应用',
    examples: ['fliggy://'],
  },
  {
    id: 'qunar',
    name: '去哪儿',
    category: 'travel',
    urlTemplate: 'qunar://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开去哪儿旅行应用',
    examples: ['qunar://'],
  },
  {
    id: 'airbnb',
    name: '爱彼迎',
    category: 'travel',
    urlTemplate: 'airbnb://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开爱彼迎民宿应用',
    examples: ['airbnb://'],
  },
  {
    id: 'booking',
    name: 'Booking',
    category: 'travel',
    urlTemplate: 'booking://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Booking酒店预订应用',
    examples: ['booking://'],
  },
  {
    id: 'tripadvisor',
    name: '猫途鹰',
    category: 'travel',
    urlTemplate: 'tripadvisor://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开猫途鹰旅游应用',
    examples: ['tripadvisor://'],
  },
  {
    id: 'maps',
    name: '地图',
    category: 'travel',
    urlTemplate: 'maps://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开系统地图应用',
    examples: ['maps://'],
  },
  // 美食应用
  {
    id: 'eleme',
    name: '饿了么',
    category: 'food',
    urlTemplate: 'eleme://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开饿了么外卖应用',
    examples: ['eleme://'],
  },
  {
    id: 'meituan',
    name: '美团',
    category: 'food',
    urlTemplate: 'meituan://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开美团外卖应用',
    examples: ['meituan://'],
  },
  {
    id: 'dianping',
    name: '大众点评',
    category: 'food',
    urlTemplate: 'dianping://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开大众点评应用',
    examples: ['dianping://'],
  },
  {
    id: 'xiachufang',
    name: '下厨房',
    category: 'food',
    urlTemplate: 'xiachufang://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开下厨房菜谱应用',
    examples: ['xiachufang://'],
  },
  {
    id: 'douyin-food',
    name: '抖音美食',
    category: 'food',
    urlTemplate: 'snssdk1128://food',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开抖音美食频道',
    examples: ['snssdk1128://food'],
  },
  {
    id: 'xiaohongshu-food',
    name: '小红书美食',
    category: 'food',
    urlTemplate: 'xhsdiscover://food',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开小红书美食频道',
    examples: ['xhsdiscover://food'],
  },
  // 娱乐应用
  {
    id: 'netease-cloud-music',
    name: '网易云音乐',
    category: 'entertainment',
    urlTemplate: 'orpheuswidget://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开网易云音乐应用',
    examples: ['orpheuswidget://'],
  },
  {
    id: 'qq-music-entertainment',
    name: 'QQ音乐',
    category: 'entertainment',
    urlTemplate: 'qqmusic://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开QQ音乐应用',
    examples: ['qqmusic://'],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'entertainment',
    urlTemplate: 'spotify://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Spotify音乐应用',
    examples: ['spotify://'],
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    category: 'entertainment',
    urlTemplate: 'music://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Apple Music应用',
    examples: ['music://'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'entertainment',
    urlTemplate: 'youtube://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开YouTube应用',
    examples: ['youtube://'],
  },
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'entertainment',
    urlTemplate: 'netflix://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Netflix应用',
    examples: ['netflix://'],
  },
  {
    id: 'disney-plus',
    name: 'Disney+',
    category: 'entertainment',
    urlTemplate: 'disneyplus://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Disney+应用',
    examples: ['disneyplus://'],
  },
  {
    id: 'steam',
    name: 'Steam',
    category: 'entertainment',
    urlTemplate: 'steam://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Steam游戏平台',
    examples: ['steam://'],
  },
  {
    id: 'epic-games',
    name: 'Epic Games',
    category: 'entertainment',
    urlTemplate: 'epicgames://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Epic Games应用',
    examples: ['epicgames://'],
  },
  // 效率应用
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    urlTemplate: 'notion://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Notion笔记应用',
    examples: ['notion://'],
  },
  {
    id: 'evernote',
    name: '印象笔记',
    category: 'productivity',
    urlTemplate: 'evernote://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开印象笔记应用',
    examples: ['evernote://'],
  },
  {
    id: 'onenote',
    name: 'OneNote',
    category: 'productivity',
    urlTemplate: 'onenote://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开OneNote笔记应用',
    examples: ['onenote://'],
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'productivity',
    urlTemplate: 'trello://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Trello项目管理应用',
    examples: ['trello://'],
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'productivity',
    urlTemplate: 'asana://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Asana项目管理应用',
    examples: ['asana://'],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'productivity',
    urlTemplate: 'slack://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Slack团队协作应用',
    examples: ['slack://'],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'productivity',
    urlTemplate: 'zoom://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Zoom视频会议应用',
    examples: ['zoom://'],
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'productivity',
    urlTemplate: 'msteams://',
    lastUpdated: '2024-01-01',
    updatedBy: 'frankie',
    description: '打开Microsoft Teams应用',
    examples: ['msteams://'],
  },
]

// 动态生成分类列表
export const CATEGORIES: Category[] = (() => {
  const counts = calculateCategoryCounts(SAMPLE_URL_SCHEMES)

  return BASE_CATEGORIES.map(category => ({
    ...category,
    count: counts[category.id] || 0,
  }))
})()
